### ISSUE TITLE
--mx doesn't scan all servers 

### ISSUE THREAD

**Issue by drwetter** [drwetter/testssl.sh#1037]
Given MX records like

```
prompt% host -t mx domain.tld
domain.tld mail is handled by 200 XX.exampleXX.net
domain.tld mail is handled by 150 YY.exampleYY.com
domain.tld mail is handled by 100 ZZ.exampleZZ.org
```

the scan initiated with ``--mx`` stops scanning after the first not available host or the first host which doesn't appear to be available (which is pretty common scanning mailservers). E.g. if ``ZZ.exampleZZ.org`` can be scanned/is available but ``YY.exampleYY.com`` cannot be scanned/has fail2ban or other measures in place,  ``XX.exampleXX.net`` will never be scanned (low number: higher priority).

This phenomena was observed using ``--mx`` only. ~~As a sanity check it needs to be clarified whether is applies to ``--file`` also~~ (**updated**)

**Comment by dcooper16** [comment]
Hi Dirk,

This issue isn't limited to just the `--mx` option, is it? If I ask testssl.sh to scan example.com and example.com resolves to multiple IP addresses, then testssl.sh will stop scanning after the first not available IP address.

**Comment by drwetter** [comment]
Hi David,

I tried via ``--file`` and used serial mass testing. That worked. Did you run a similar test or a different one.

Dirk

**Comment by dcooper16** [comment]
Hi Dirk,

No, I didn't run any tests.

I agree that this isn't an issue for mass testing. Suppose I use the `--file <fname>` option, and <fname> contains three lines (example.com, www.example.com, html.example.com). If the IP address for example.com is not available, then the child process created to test example.com will exit, but the parent process will continue to run and will run tests for www.example.com and html.example.com.

The scenario I was considering was one in which testssl.sh is called as `testssl.sh example.com` and a DNS lookup for example.com returns three IP addresses: 192.0.2.1, 192.0.2.2, and 192.0.2.3.

The main body of testssl.sh will run a `for` loop over the IP addresses (just printing "Testing all IPv4 addresses (port $PORT):", calling `lets_roll()` for each IP address. If 192.0.2.1 has connectivity problems, then the program will `exit`, and so 192.0.2.2 and 192.0.2.3 will not be tested.

It's the same issue as with `--mx`, except that the `for` loop is in the main body of program (starting at line 17337) rather than in `run_mx_all_ips()`.

**Comment by drwetter** [comment]
> It's the same issue as with ``--mx``, except that the ``for`` loop is in the main body of program (starting at line 17337) rather than in ``run_mx_all_ips()``.

Ah ok. :( Thanks

**Comment by drwetter** [comment]
This proved to be more difficult than I thought. A brain dump follows.

``fatal()`` is a shortcut to the exit also for connectivity problems. Unless we change the logic of the for loops to exec the IPs to be checked as children we can't use ``fatal()`` directly but need to check whether there are other IPs to check

**Comment by drwetter** [comment]
see 966f414 . TLDR: picked \#2
