### ISSUE TITLE
cannot exec or find any openssl binary with or without --openssl specified

### ISSUE THREAD

**Issue by yaleman** [drwetter/testssl.sh#1061]
1. **testssl version from the banner:** From script, as -b won't run: `readonly VERSION="2.9.5"`

2. **what exactly was happening**: Won't run on kali with self-compiled openssl:

```
$ testssl --openssl /opt/openssl/bin/openssl -b
Fatal error: cannot exec or find any openssl binary
$ /opt/openssl/bin/openssl version
OpenSSL 1.1.0h  27 Mar 2018
```

3. **what did you expect instead?** Banner should be displayed (doesn't matter what I try)
4. **steps to reproduce**
   1. _testssl.sh command line:_ `testssl --openssl /opt/openssl/bin/openssl -b`
   1. _openssl version used:_ `OpenSSL 1.1.0h  27 Mar 2018` (compiled from source tonight)
   1. _your operating system:_ Kali `$ uname -a Linux stinky 4.15.0-kali3-amd64 #1 SMP Debian 4.15.17-1kali1 (2018-04-25) x86_64 GNU/Linux`
   1. _lsb_release output:_ 
    ```
    $ lsb_release -a
    No LSB modules are available.
    Distributor ID:	Kali
    Description:	Kali GNU/Linux Rolling
    Release:	kali-rolling
    Codename:	kali-rolling
    ```
**Other notes:**
- aforementioned openssl binary is in path, works for any test I can figure out

**Comment by drwetter** [comment]
General answer: Sorry, can't help you with this problem. This is a setup/configuration problem. If testssl claims it cannot exec or find any openssl binary it just can't  exec or find any openssl binary.

Personally I was curious though whether kali screwed something up. Tried myself with a pull from github. Works like a charm. 

Two remarks: 1) Kali is way behind. At least you should pull the latest 2.9.5 from github. Don't know what the point of a rolling release is then. 2) There's in general no or at least little need to compile openssl yourself anymore since 2.9x.

**Comment by yaleman** [comment]
This was the latest version pulled straight from your site with wget ... :(

**Comment by drwetter** [comment]
> I might not have explained that well - wget'd it from the site and ran it because of the old version in kali...

that will work too. Wonder why you then refer to it as ``testssl`` and not ``testssl.sh``. Is it executable? You're sure you're running the dl'ed version (no absolute path)?

Then there's a contradiction: a) ``From script, as -b won't run: readonly VERSION="2.9.5"`` b) 
```
testssl --openssl /opt/openssl/bin/openssl -b
Fatal error: cannot exec or find any openssl binary
```

**Comment by yaleman** [comment]
I honestly don't know what I did in between testing it last time and now, but it's working after re-downloading the script and running it fresh. I *had* downloaded it without the .sh and was running it out of the working directory - in my haste to strip my shell info I stripped that too.

Apologies :(

Thanks for the amazing tool!
