### ISSUE TITLE
BEAST + wide: 1x LF too much

### ISSUE THREAD

**Issue by drwetter** [drwetter/testssl.sh#1069]
```
 SSLv2      not offered (OK)
 SSLv3      not offered (OK)
 TLS 1      not offered
 TLS 1.1    not offered
 TLS 1.2    offered (OK)
 TLS 1.3    not offered
 NPN/SPDY   http/1.1 (advertised)
 ALPN/HTTP2 http/1.1 (offered)

[..]
 LOGJAM (CVE-2015-4000), experimental      not vulnerable (OK): no DH EXPORT ciphers, no DH key detected
 BEAST (CVE-2011-3389)                     no SSL3 or TLS1 (OK)

 LUCKY13 (CVE-2013-0169), experimental     potentially VULNERABLE, uses cipher block chaining (CBC) ciphers with TLS. Check patches
 RC4 (CVE-2013-2566, CVE-2015-2808)        no RC4 ciphers detected (OK)
```

**Comment by dcooper16** [comment]
Hi Dirk,

I believe the problem is actually with LUCKY13 and not BEAST. In particular, lines 13976 - 13978 of `run_lucky13()`:
```
     if [[ $VULN_COUNT -le $VULN_THRESHLD ]] || "$WIDE"; then
          outln
     fi
```
The change was made in this commit: https://github.com/drwetter/testssl.sh/commit/37c8ee8c4e99ee5aa11618703af1706abcf5db04. For some reason this commit removed the `|| "$WIDE"` from `run_beast()` and `run_rc4()`, but added it to `run_lucky13()`. Maybe it was a copy/paste error.

The code in `run_beast()` and `run_rc4()` is also now a bit odd. For example, in `run_beast()` it is
```
     if [[ $VULN_COUNT -le $VULN_THRESHLD ]]; then
          outln
          pr_headlineln " Testing for BEAST vulnerability "
     fi
     if [[ $VULN_COUNT -le $VULN_THRESHLD ]]; then
          outln
     fi
```
Couldn't this be simplified to something like
```
     [[ $VULN_COUNT -le $VULN_THRESHLD ]] && pr_headlineln "\n Testing for BEAST vulnerability\n"
```
The same applies for `run_rc4()`.

**Comment by drwetter** [comment]
Hi David,

thanks for looking into it. Looks you're right ;-)

Guess the other places you spotted have historical reasons somehow. 
Call it a day though now, rather fix that if I have more sleep...

Thx again, Dirk
