### ISSUE TITLE
Detect and fix TLS 1.3 handshake in sclient_connect_successful()

### ISSUE THREAD

**Issue by drwetter** [drwetter/testssl.sh#1118]
`` sclient_connect_successful()`` is for SSL 3 to TLS 1.2.  There's no Master Key in TLS 1.3. Also the logic for TLS 1.3 handshake is different. As a result:

```
./testssl.sh --ip=one -P --openssl /data/tmp/openssl.git/apps/openssl testssl.net

No engine or GOST support via engine with your <redacted>openssl
###########################################################
    testssl.sh       3.0rc1 from https://testssl.sh/dev/
    (5de89ae 2018-09-05 16:48:28 -- )

      This program is free software. Distribution and
             modification under GPLv2 permitted.
      USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!

       Please file bugs @ https://testssl.sh/bugs/

###########################################################

 Using "OpenSSL 1.1.1-pre10-dev  xx XXX xxxx" [~189 ciphers]
 on <redacted>
 (built: "Aug 21 14:57:12 2018", platform: "linux-x86_64")

 Start 2018-09-10 07:54:43        -->> 104.18.34.81:443 (testssl.net) <<--

 Further IP addresses:   104.18.35.81 2400:cb00:2048:1::6812:2251 2400:cb00:2048:1::6812:2351 
 A record via:           supplied IP "104.18.34.81"
 rDNS (104.18.34.81):    --
 Service detected:       HTTP


 Testing server preferences 

 Has server cipher order?     yes (OK)
 Negotiated protocol          default proto empty
 Negotiated cipher            default cipher empty, 253 bit ECDH (X25519)
 Cipher order
    TLSv1:     ECDHE-ECDSA-AES128-SHA ECDHE-ECDSA-AES256-SHA 
    TLSv1.1:   ECDHE-ECDSA-AES128-SHA ECDHE-ECDSA-AES256-SHA 
    TLSv1.2:   ECDHE-ECDSA-CHACHA20-POLY1305-OLD ECDHE-ECDSA-CHACHA20-POLY1305 ECDHE-ECDSA-AES128-GCM-SHA256 ECDHE-ECDSA-AES128-SHA ECDHE-ECDSA-AES128-SHA256 ECDHE-ECDSA-AES256-GCM-SHA384
               ECDHE-ECDSA-AES256-SHA ECDHE-ECDSA-AES256-SHA384 
    TLSv1.3:   TLS_AES_256_GCM_SHA384 TLS_CHACHA20_POLY1305_SHA256 TLS_AES_128_GCM_SHA256 


 Done 2018-09-10 07:54:50 [  19s] -->> 104.18.34.81:443 (testssl.net) <<--
```

 See ``default proto empty`` and ``default cipher empty``.  

This is a leftover of #1115 .

**Comment by dcooper16** [comment]
Hi Dirk,

I just tried running this and encountered the same results, but for a different reason. The call to `$OPENSSL s_client` is returning 0, and so `sclient_connect_successful()` is returning 0. The problem is that `get_cipher()` and `get_protocol()` are returning empty strings.

It seems that when `$OPENSSL s_client` negotiates TLS 1.2 or earlier it outputs some lines of the form:
```
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-ECDSA-CHACHA20-POLY1305
    Session-ID: BFEC9659BCC2B1C46B1E4954F931EA01DEC8D7077B56E77745628E72FCF63EC0
    Session-ID-ctx: 
    Master-Key: 2B301D7BE35F861ACA0AC83872905580F1E85AEE7E4997F7A48DDBA3BC97F2FC552944B80E6ED2B2539BF6D8CCADA9DB
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 64800 (seconds)
    TLS session ticket:
    ...
```
`get_cipher()` and `get_protocol()` extract the cipher and the protocol from this information. However, this "SSL-Session" information isn't printed when TLS 1.3 is negotiated. Instead, the cipher and protocol are only included in the following line:
```
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
```
So, it seems that `get_cipher()` and `get_protocol()` need to be modified to extract the cipher and protocol from this line, at least when TLS 1.3 is negotiated.

**Comment by dcooper16** [comment]
After some more testing it seems that OpenSSL will print out the "SSL-Session" information for TLS 1.3 if a post-handshake new session ticket is received. So, the current `get_cipher()` and `get_protocol()` will sometimes work for TLS 1.3, but not always.

**Comment by drwetter** [comment]
@dcooper16 : some

**Comment by dcooper16** [comment]
> something is fishy. Don't know whether I'll have time during the weekend but testssl.sh --ip=one -P --openssl openssl111 testssl.net returns to me no cipher order.

I just did some testing against testssl.sh, and it is odd. It seems that testssl.sh has a cipher order for TLSv1.2, but not for TLSv1.3. If you send a TLSv1.2 ClientHello to testssl.sh, then the server will choose _its_ preferred cipher, regardless of the order the ciphers appear in the ClientHello. However, if you send a TLSv1.3 ClientHello, the server choose whichever TLSv1.3 cipher appears first in the ClientHelllo.

So, testssl.sh is providing different results depending on whether OpenSSL 1.0.2 or 1.1.1 is used since one is testing whether the server has a cipher order for TLSv1.2 and the other is testing whether the server has a cipher order for TLSv1.3.

**Comment by drwetter** [comment]
As you indicated, we are fine here but it's not us which are odd. ;-)

testssl.sh works as expected here as the cloudflare instance of my server testssl.sh -- which is testssl.net -- just doesn't provide a cipher order for TLS 1.3. For 1.2 it does. That seems the only odd thing.

Using the supplied binary it tests only the server preference for <= TLS 1.2, using OpenSSL version 1.1.1 it adds to s_client ``-ciphersuites TLS_AES_256_GCM_SHA384:TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256`` and then turns it upside down. The server side for testssl.net however doesn't care.

I experimented a bit with Debian SID but can't reproduce what CF does. This maybe related to https://trac.nginx.org/nginx/ticket/1529. But as indicated with Debian SID (OpenSSL 1.1.1a and nginx 1.14.1) that is not what I see.

Given what cloudflare does and how OpenSSL works I think the server preference test needs to be split between TLS 1.3 and <= TLS 1.2.
