### ISSUE TITLE
How can i know the type of certificate?

### ISSUE THREAD

**Issue by empqruy** [drwetter/testssl.sh#1155]
There are DV SSL, OV SSL and EV SSL; how can i know the type of certificate form the testssh output?

----Banner
 
###########################################################
    testssl.sh       2.9.5-7 from https://testssl.sh/

      This program is free software. Distribution and
             modification under GPLv2 permitted.
      USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!

       Please file bugs @ https://testssl.sh/bugs/

###########################################################

 Using "OpenSSL 1.0.2-chacha (1.0.2i-dev)" [~183 ciphers]
 on 172-16-36-108:./bin/openssl.Linux.x86_64
 (built: "Jun 22 19:32:29 2016", platform: "linux-x86_64")

**Comment by drwetter** [comment]
I should encourage others more to answer....

For EV there's a check if you look at _Testing server defaults_ --> _EV cert_ . It's labled as "Experimental" as there might be policy OIDs which are missing.

For DV there's no possibility of detection, at least not that I know of.
 
Independent on that: The type of certificate probably never had a 100% reliable message in terms of security. Nowadays the difference -- green bar with company name--  gets even smaller as mobile clients don't show any difference. Safari is supposedly dropping the green bar or has already, Chrome makes it currently depended on the support of certificate transparency. 

IMO it's just a matter whether Google, Mozilla and maybe others resist the lobbying of EV certificate sellers.

HTH, Dirk

**Comment by teward** [comment]
@drwetter Correct me if I'm wrong, but don't DV certs by their very existence of being signed by a major trusted CA need DV?  EV requires the experimental OID detection, yes, but as I understand it, standard CAs - Let's Encrypt and others included - need to at least get Domain Validation done to issue a certificate, except for their own intermediate certs or their own root certs.  Isn't this a given?  (Therefore all certs unless otherwise specified would need to be considered DV certs)

**Comment by drwetter** [comment]
@teward : did I say something different?
