### ISSUE TITLE
JSON file error - No separators (,) between targetHosts objects

### ISSUE THREAD

**Issue by felmoltor** [drwetter/testssl.sh#1243]
On the JSON output file, there is no delimiter between targetHosts objects, so the parsing of the file fails with python json library with the following message:

```
In [23]: json.load(open("testssl.targets.port.443.json","r"))
[...]
ValueError: Expecting , delimiter: line 8068 column 11 (char 519745)
```

Example of current JSON file:
```
[...]
                           },{
                                "id"           : "clientsimulation-openssl_102e",
                                "severity"     : "INFO",
                                "finding"      : "TLSv1.2 ECDHE-RSA-AES256-SHA384"
                           }
                    ]
-->       }
-->       {
                    "targetHost"      : "<IP>",
                    "ip"              : "<IP>",
                    "port"            : "443",
[...]
```
Between the two pointed curly braces there should be a comma.

1. uname -a
Linux felipe-host 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3 (2019-02-02) x86_64 GNU/Linux
   
2. testssl version from the banner: testssl.sh -b 2>/dev/null | head -4 | tail -2
testssl.sh       3.0rc4 from https://testssl.sh/dev/

3. git log | head -1 (if running from git repo)
commit bc6b2c6f94dc6a76f9cc9951a601dbc020f97b6b

4. openssl version used by testssl.sh: 
Using "OpenSSL 1.0.2-chacha (1.0.2k-dev)"

5. steps to reproduce: testssl.sh or docker command line, if possible incl. host
Scan multiple IP hosts and output the results to JSON with the flag -oA.

**Comment by dcooper16** [comment]
Hi @felmoltor,

Thanks for reporting. I believe that I've discovered two problems related to you issue. When performing testing on multiple servers, `create_mass_testing_cmdline()` is supposed to rewrite the command line for each server to be tested, and this function was not updated when the `-oA` option was added. It also does not handle the `-oj` or `-oJ` options if the `--parallel` option was not used.

If you specify `-oA auto`, that seems to work, but specifying a filename doesn't.

I'll look into a fix for this, but in the meantime, I think you can avoid the problem by specifying each option separately rather than using `-oA`, i.e., using `-oL <logfile> -jsonfile-pretty <jsonfile> -oC <csvfile> -oH <htmlfile>`.
