### ISSUE TITLE
[make-openssl111.sh] "enable-tls13downgrade" doesn't exist anymore

### ISSUE THREAD

**Issue by pihug12** [drwetter/testssl.sh#1294]
https://github.com/drwetter/testssl.sh/blob/3.0/utils/make-openssl111.sh#L15

`enable-tls13downgrade` doesn't exist since July 18, 2018: https://github.com/openssl/openssl/commit/9f22c527232d8babfa4827dff34a6707e8880dd9#diff-6a755e7d228a2b491321dbae0a7a248b

It makes the script/build failed.

____

And are the lines 85-87 correct (https://github.com/drwetter/testssl.sh/blob/3.0/utils/make-openssl111.sh#L85-L87) without the `-static`?

**Comment by drwetter** [comment]
Hi @pihug12,

the first point I discovered too but didn't bother yet to change. A while back this file was provided as a courtesy. It's a good idea to change that now.

The second point was just my sloppiness as one distribution won't link the binary otherwise. But that line should change.

Mind providing a PR?

Cheers, Dirk
