### ISSUE TITLE
Show peer signing digest / signed_params hash function

### ISSUE THREAD

**Issue by djcater** [drwetter/testssl.sh#1519]
OS: `Ubuntu 19.10`

testssl.sh version:
```
testssl.sh       3.0 from https://testssl.sh/
(4dbd9a9 2020-02-15 15:23:07 -- )
commit 4dbd9a98ba503f624b24d00629da0e98d655021c
```
OpenSSL used:
```
./bin/openssl.Linux.x86_64
```
Chrome is looking to deprecate the RSA SHA-1 signing digest: https://bugs.chromium.org/p/chromium/issues/detail?id=658905

This is not the signature algorithm of the certificate, nor the HMAC of the cipher suite, but (I think) the algorithm used to sign the server parameters during the handshake.

An example site (taken from this Mozilla ticket: https://bugzilla.mozilla.org/show_bug.cgi?id=1600449) is https://www.daserste.de/.

In the Firefox developer tools, you can see in the "Network" tab of a request, and then in the "Security" sub-tab, it says: "Signature Scheme": `RSA-PKCS1-SHA1`.

This can also be seen in the OpenSSL output:
```
openssl s_client -connect www.daserste.de:443 -servername www.daserste.de
```
```
Peer signing digest: SHA1
Peer signature type: RSA
```
There is a ticket for adding this to SSL Labs here: https://github.com/ssllabs/ssllabs-scan/issues/465

It would be really useful to add to testssl.sh. Thank you.

**Comment by dcooper16** [comment]
This seems like something that would be a useful addition, but some thought would have to be given as to how to present this information. As you noted, this is the hash algorithm used when signing the ephemeral public key in the ServerKeyExchange message for non-anonymous PFS ciphers. So, it seems that the information should appear in the PFS section, along with the set of "robust" PFS ciphers supported, the set of ECDH curves supported, and the set of DH groups supported.

Some thought would be need to be given about what information to provide and how to provide it.

In TLS 1.3, the signature appears in the CertificateVerify message rather than the ServerKeyExchange. Should testssl.sh show both of these. For TLS 1.1 and below, there isn't a choice of hash algorithm. For RSA the hash is SHA1+MD5 and for (EC)DSA it is SHA-1. Should the hash algorithms used with TLS 1.1 and earlier be shown.

For TLS 1.2 the signature algorithm used by the server may depend on the contents on the signature_algorithms extension in the ClientHello. Should testssl.sh try various contents for the ClientHello signature_algorithms extension and display all of the options supported by the server, or should testssl.sh just send a signature_algorithms extension that indicates support for all signature algorithms and just display the algorithm that the server chooses in that case?

**Comment by Phil2407** [comment]
> For TLS 1.2 the signature algorithm used by the server may depend on the contents on the signature_algorithms extension in the ClientHello. Should testssl.sh try various contents for the ClientHello signature_algorithms extension and display all of the options supported by the server, or should testssl.sh just send a signature_algorithms extension that indicates support for all signature algorithms and just display the algorithm that the server chooses in that case?

As far as I can tell the recently merged pull request shows only the chosen algorithm. Is showing a list of all algorithms supported by the server still something being worked on? Showing that information would be very helpful.

**Comment by dcooper16** [comment]
> As far as I can tell the recently merged pull request shows only the chosen algorithm. Is showing a list of all algorithms supported by the server still something being worked on? Showing that information would be very helpful.

I'm not sure which pull request you're referring to, but I haven't had a chance to work on this issue yet. #1642 extracts the algorithm used by the server in order to enable this issue to be worked on, but it wasn't intended to be a resolution for this issue.
