### ISSUE TITLE
testssl hangs

### ISSUE THREAD

**Issue by saikrishna4d8** [drwetter/testssl.sh#1551]
I have tried the below command 
testssl.sh --quiet --openssl-timeout=90 -s -S -A -O -C 103.212.28.94:443
and it just hunged, and i tried for other Ip address, it works without any issue. I am using testssl.sh-3.0

**Comment by drwetter** [comment]
Thanks for the report. (please use the template next time).

Just had a short look, and I doesn't seem to hang, it loops over and over in the BEAST check (using 3.1dev).

**Comment by saikrishna4d8** [comment]
Hi @drwetter 
Sorry for not using the template, I tried it in 3.1 dev branch but facing the same issue.

**Comment by dcooper16** [comment]
I just looked into this and believe that I found the bug. This server supports a CBC cipher for which there is no OpenSSL name: SSL_RSA_FIPS_WITH_3DES_EDE_CBC_SHA. `parse_tls_serverhello()` normally writes out the selected cipher's OpenSSL name (to align with OpenSSL s_client's output), but writes out the RFC name if there is no OpenSSL name.

The above rare event triggered two bugs. First, `get_cipher()` doesn't handle RFC names, since it was written to parse only OpenSSL names. So, when it is presented with a file containing an RFC name, it doesn't find the cipher name. Second, the code in `run_beast()` that calls `get_cipher()` didn't include code to handle the possibility that `get_cipher()` didn't work. These two bugs combine to cause `run_beast()` to get stuck in an infinite loop.

I'll work on a fix for these two issues.

**Comment by dcooper16** [comment]
It seems that my original understanding of the bug was incorrect. `parse_tls_serverhello()` always writes out the RFC name, and `get_cipher()` was designed to handle such names. The problem was that `get_cipher()` was not designed to handle RFC names that begin with SSL_. There are only four non-SSLv2 cipher suites with RFC names that begin with SSL_: SSL_RSA_FIPS_WITH_DES_CBC_SHA (xFEFE), SSL_RSA_FIPS_WITH_3DES_EDE_CBC_SHA (xFEFF),  SSL_RSA_FIPS_WITH_3DES_EDE_CBC_SHA (xFFE0), and SSL_RSA_FIPS_WITH_DES_CBC_SHA (xFFE1). Since these four cipher suites are rarely supported by servers, the bug rarely caused problems.

Anyway, I submitted PR #1556 and PR #1557 to fix this problem in both the 3.1dev branch and the 3.0 branch.

**Comment by drwetter** [comment]
Thanks for the fixes @dcooper16 !

**Comment by saikrishna4d8** [comment]
Thank you @drwetter & @dcooper16
