### ISSUE TITLE
Unicode artifacts in https://testssl.sh/testssl.1.html (latin1 vs. utf8)

### ISSUE THREAD

**Issue by adaugherity** [drwetter/testssl.sh#1701]
Technically, this is an issue with your web server configuration, not the testssl code, but this seems like the best place to report.

The [man page](https://testssl.sh/testssl.1.html) is a utf8 document, but is being served as latin1, which causes Unicode artifacts in (at least) the copyright section, which displays as "**Copyright Â© 2012 Dirk Wetter**."  If I manually set my browser to utf8, then it displays correctly.

The file contains charset meta tags, but I believe those are only used for local documents and are ignored for HTTP connections, where the server must set a charset in the Content-Type header; absent such a header, the browser uses its default charset (latin1).

**Comment by drwetter** [comment]
Thanks, @adaugherity . In fact there was a meta tag in the HTML section. However instead of  

``<meta http-equiv="Content-Type" content="text/html; charset=utf-8">`` 

it was 

``<meta http-equiv='content-type' value='text/html;charset=utf8'>``

That came from ronn. I am not completely happy with it for several reasons. This is another thing I need to keep in mind when I do the conversion from md to html.

Thanks again, Dirk
