### ISSUE TITLE
Remove spaces from certificates in JSON

### ISSUE THREAD

**Issue by drwetter** [drwetter/testssl.sh#1747]
Currently certificates in JSON output look like 

``
-----BEGIN CERTIFICATE----- MIIFXDCCBESgAw[..]foACzLsvA
aJ2+MA0GCSqGSIb3DQEBCwUA MEoxCzAJBgNV[..]eXB0MSMwIQYDVQQD ExpMZXQnc[..] ``

As a convenience feature it would be great of the spaces in the certificate string itself could be removed. That could save later a bit of work when putting it together. Or even omit the BEGIN / END line as MS' ADFS does it (/federationmetadata/2007-06/federationmetadata.xml)

**Comment by keisentraut** [comment]
The pull request above was not merged because it did not have the necessary quality. This issue is still open. It should be fixed like this:
>Then, sorry, while looking at it again I think now it's not handy to remove also the leading and trailing line because otherwise it's a bit of a headache putting it together again for openssl, just played with it. What I think is better having the output as
>
>-----BEGIN CERTIFICATE-----\nMIIE[one line with base64 encoded certificate without any blanks..]\n-----BEGIN CERTIFICATE-----
>
>That one can just feed to openssl and it happily swallows that.

**Comment by dcooper16** [comment]
Hi Dirk,

I tried to create a PR to address this issue, but ran into a problem as a result of #2050. I can't figure out a way to include '\n' in a string that won't get removed by #2050.

I can see two possible solutions. The first would be to move the change in #2050 to `fatal()`, and then ensure that `fileout()` is never called with a string  that includes '\n' that would be converted to a newline character by `fileout_json_finding()` and `fileout_csv_finding()`.

The second solution would be to add include the fix for PEM encoded data in `fileout()` immediately after the line added by #2050. (The solution that you didn't like in #1767). If we were to go with the second solution, then rather than looking for a specific value in the id field, I would suggest checking the `$finding` to see if it appears to contain PEM-encoded data:
```
[[ "$finding" =~ -+BEGIN\ [A-Za-z0-9]*-+\ .+\ -+END\ [A-Za-z0-9]*-+ ]] && finding="$(pem_to_one_line "$finding")
```
I don't think testssl.sh sends PEM-encoded data to `fileout()` except in the two places where it sends certificates, but the second solution any new calls to `fileout()` that were added that had PEM-encoded data.

Do you have a preference for which of these two solutions to use?
