### ISSUE TITLE
FEATURE REQUEST - Provide custom request headers 

### ISSUE THREAD

**Issue by chrisdlangton** [drwetter/testssl.sh#1770]
Many endpoints are more commonly relying on a customer header to establish a TLS connection, without the header the connection will be dropped or 403 http code response sent.

I understand basicauth via Authorization header can already be added, this requested capability would do the same but not use a hard coded header name.

**Comment by drwetter** [comment]
How does that work? HTTP header comes in the TLS packet.

**Comment by pnieuwkamp** [comment]
I think Chris may not mean the actual establishment of the TLS connection, but the request that gets send after the connection is made. Some web services rely on a different header than the Authorization one to establish authorization. For instance, I have one that requires me to insert a HTTP header like: "ClientID: 0xDEADBEAF" otherwise it will not process the request.

**Comment by chrisdlangton** [comment]
correct, the response headers will not be sent without the correct/expected request headers

**Comment by drwetter** [comment]
ok, that's no big deal

**Comment by drwetter** [comment]
See PR merged above

**Comment by chrisdlangton** [comment]
Legend @drwetter 
Bash master smashes another feature

**Comment by chrisdlangton** [comment]
Legend @drwetter this'll be a huge benefit for so many environments
Bash master @tosticated smashes another feature
