### ISSUE TITLE
SSLv2 in run_preferences()

### ISSUE THREAD

**Issue by drwetter** [drwetter/testssl.sh#1779]
If I run testssl.sh against a server which uses our testssl.sh the SSLv2 ciphers are not recognized in the SSLv2 section of run_preferences(). 

![image](https://user-images.githubusercontent.com/8036727/99704359-9483e700-2a98-11eb-9779-76e443d02c37.png)

using ``--ssl-native`` works.

Using 3.0 ``-p -E`` shows the same behavior:

![image](https://user-images.githubusercontent.com/8036727/99704811-2be93a00-2a99-11eb-9c55-4d927b935c26.png)

**Comment by dcooper16** [comment]
Hi Dirk,

I believe the source of the problem is https://github.com/drwetter/testssl.sh/commit/3cd1273439595603100e199422e03aa83c5fd862 and https://github.com/drwetter/testssl.sh/commit/3c97412a61f70749c1e0d770bf365aa3c6a8e780. These commits replace:
```
response_len=$(wc -c "$SOCK_REPLY_FILE" | awk '{ print $1 }')
```
with
```
count_chars() {
     echo $(wc -c <<< "$1")
}

response_len=$(count_chars "$SOCK_REPLY_FILE")
```
The result is that `$response_len` is being set to the length of the file name specified by `$SOCK_REPLY_FILE` rather than by the length of the contents of the file. The problem occurs when `sslv2_sockets()` is called from `ciphers_by_strength()` but not `run_protocols()`, since the call from `ciphers_by_strength()` sets `$parse_complete` to `true`, but the call from `run_protocols()` does not.

I haven't tried correcting the error, but my guess is that things will work again if this error is corrected.

**Comment by drwetter** [comment]
Hi David,

as often you're right ;-) Fix is on the way.

For @ all: there will be later today a stable version <s>3.0.3.1</s> 3.0.4.

Cheers, Dirk

**Comment by drwetter** [comment]
thanks, David!
