### ISSUE TITLE
[BUG] "Bad file descriptor" with --connect-timeout option

### ISSUE THREAD

**Issue by fogs** [drwetter/testssl.sh#1834]
**Please check this repo whether this is a known issue**
Maybe related to https://github.com/drwetter/testssl.sh/issues/1435 but happens regardless of parallel scans

**Command line / docker command to reproduce**
docker run --rm -ti  drwetter/testssl.sh:3.0 -p --connect-timeout 10 drwetter.eu

**Expected behavior**
No error message "Bad file descriptor"
Same output as docker run --rm -ti  drwetter/testssl.sh:3.0 -p drwetter.eu

**Your system (please complete the following information):**
 - OS: Ubuntu 20.10
 - Platform: Linux 5.8.0-38-generic x86_64
 - Version: testssl.sh       3.0.4 from https://testssl.sh/
 - OpenSSL: /home/testssl/bin/openssl.Linux.x86_64

**Comment by drwetter** [comment]
thanks.

@goncalor : FYI

**Comment by Max7cd** [comment]
Hey @drwetter 

I came across the same bug as many others have by now when adding the connect-timeout flag to my script and I think I have figured out the problematic part.

I tracked it down to this part of the code: (line 11106 - line 11121 on commit f253920e920)
```bash
elif [[ -n "$CONNECT_TIMEOUT" ]]; then
     if ! $TIMEOUT_CMD $CONNECT_TIMEOUT bash -c "exec 5<>/dev/tcp/$nodeip/$PORT"; then
          ((NR_SOCKET_FAIL++))
          connectivity_problem $NR_SOCKET_FAIL $MAX_SOCKET_FAIL "TCP connect problem" "repeated TCP connect problems (connect timeout), giving up"
          outln
          pr_warning "Unable to open a socket to $NODEIP:$PORT. "
          return 6
     fi
     # Now comes the usual case
elif ! exec 5<>/dev/tcp/$nodeip/$PORT; then
     ((NR_SOCKET_FAIL++))
     connectivity_problem $NR_SOCKET_FAIL $MAX_SOCKET_FAIL "TCP connect problem" "repeated TCP connect problems, giving up"
     outln
     pr_warning "Unable to open a socket to $NODEIP:$PORT. "
     return 6
fi
```

Now I am not very good at coding in shell so please forgive me if I am overlooking something obvious here.
The big difference is the `bash -c` when running exec to replace the current bash process with the right part.
So now as I understand the bash docs, bash -c starts a new subshell and executes the command there. Then exec is executed inside this subshell instead of the process of our program. This then leads to the bad file descriptor and (maybe?) to the other problems.

As I have said, I'm not very good at bash, so I dont know if there is some way to work around this, but at first glance it does not look like it to me, since `timeout` requires a command to be run and exec is a bash builtin that needs to run in the current process.

Unless you have some good idea for a fix, I will probably just use `timeout $MY_TIMEOUT testssl.sh $MY_ARGS` to workaround this.

**Comment by drwetter** [comment]
Hi there @Max7cd ,

thanks. Yes, that was also my rough analysis a while back in #1435. I then didn't mange to get the fd exported. 

When looking at it later (=now) however I think that if it cannot be exported (TBD -- I am not a wizard as far as that is concerned either),  changing the logic is an alternative:

```diff
@@ -11111,8 +11111,9 @@ fd_socket() {
pr_warning "Unable to open a socket to $NODEIP:$PORT. "
return 6
fi
+     fi
# Now comes the usual case
-     elif ! exec 5<>/dev/tcp/$nodeip/$PORT; then
+     if ! exec 5<>/dev/tcp/$nodeip/$PORT; then
((NR_SOCKET_FAIL++))
connectivity_problem $NR_SOCKET_FAIL $MAX_SOCKET_FAIL "TCP connect problem" "repeated TCP connect problems, giving up"
outln
```
which means "trying a connect with that timeout. If that worked forget the fd and just try again without timeout". It costs 1x additional connect which is ok.


Opinions?

**Comment by drwetter** [comment]
@Max7cd : As I only experienced this while doing mass scans: which is your scenario when it fails?

**Comment by drwetter** [comment]
Please test PR #2047 if possible

**Comment by Max7cd** [comment]
thanks for the fast feedback :)

Here is the command I'm using so that it fails: `testssl.sh --connect-timeout 30 -p -t smtp ex2k10.rpnl.de.:25`
So basically just connect-timeout without anything special.
I have tried the fix in fix_badFileDescriptor and it does not throw the file descriptor error anymore. Unfortunately I don't have the url of the server that just kept the connection up indefinitely right now. I will probably come across it when I have time to work on the project again, and then I can tell you if the timeout/fix works.
Thank you very much for developing this awesome project.

Just for completeness:
OS: Manjaro Linux 5.10.79
Platform: x86_64
Version: testssl.sh 3.1dev f253920e920c548f9da75f75e06344383819c0b2
OpenSSL: OpenSSL 1.0.2-chacha (1.0.2k-dev) (provided by testssl.sh)

**Comment by drwetter** [comment]
Ok, thanks! Please let me know of any new results.

Cheers, Dirk

**Comment by Max7cd** [comment]
Hey Dirk,

So I just tested it with a server that kept the connection alive for way too long and your fix seems to work!
Thank you very much. 

The problem the server has, is that it actually does not have a smtp server running/port open, so it just hangs.
`mail2.klinikum-nuernberg.de.:25` is the server I was trying out, if you want to try it out yourself.

**Comment by drwetter** [comment]
Thanks, @Max7cd . But that worked already before, other than your previous example ``testssl.sh --connect-timeout 30 -p -t smtp ex2k10.rpnl.de.:25`` which did not.

@ anybody else can do a short test of the ``fix_badFileDescriptor`` branch?

**Comment by goncalor** [comment]
Hey. I've tested it. Seems to work okay now :)

With `3.1dev`:
```
$ docker run --rm -ti testssl:3.1dev --quiet --connect-timeout 10 -p drwetter.eu

 Start 2021-11-28 12:28:31        -->> 81.169.166.184:443 (drwetter.eu) <<--

 Further IP addresses:   2a01:238:4308:a920:1337::3 
 rDNS (81.169.166.184):  testssl.sh.
/usr/local/bin/testssl.sh: line 11258: 5: Bad file descriptor
/usr/local/bin/testssl.sh: line 11258: 5: Bad file descriptor
/usr/local/bin/testssl.sh: line 11258: 5: Bad file descriptor
/usr/local/bin/testssl.sh: line 11258: 5: Bad file descriptor
^C
$ 
```

With `fix_badFileDescriptor`:
``` 
$ docker run --rm -ti testssl:fix_badFileDescriptor --quiet --connect-timeout 10 -p drwetter.eu

 Start 2021-11-28 12:28:46        -->> 81.169.166.184:443 (drwetter.eu) <<--

 Further IP addresses:   2a01:238:4308:a920:1337::3 
 rDNS (81.169.166.184):  testssl.sh.
 Service detected:       HTTP


 Testing protocols via sockets except NPN+ALPN 

 SSLv2      not offered (OK)
 SSLv3      not offered (OK)
 TLS 1      not offered
 TLS 1.1    not offered
 TLS 1.2    offered (OK)
 TLS 1.3    offered (OK): final
 NPN/SPDY   h2, http/1.1 (advertised)
 ALPN/HTTP2 h2, http/1.1 (offered)


 Done 2021-11-28 12:29:04 [  22s] -->> 81.169.166.184:443 (drwetter.eu) <<--


```
