### ISSUE TITLE
Question: Negotiated Cipher yellow ECDHE-RSA-AES256-SHA384, 521 bit ECDH

### ISSUE THREAD

**Issue by logopk** [drwetter/testssl.sh#192]
Hi there,

I've got yellow "ECDHE-RSA-AES256-SHA384" and green "521 bit ECDH". The server has TLS1.2.

The code shows "# it's CBC. --> lucky13". Is yellow in this case correct?

Best regards.

Peter

                pr_bold " Negotiated cipher            "
                default_cipher=$(grep -aw "Cipher" $TMPFILE | egrep -avw "New|is" | sed -e 's/^.*Cipher.*://' -e 's/ //g')
                case "$default_cipher" in
                        *NULL*|*EXP*)   pr_red "$default_cipher" ;;
                        *RC4*)          pr_litered "$default_cipher" ;;
                        *CBC*)          pr_brown "$default_cipher" ;;   # FIXME BEAST: We miss some CBC ciphers here, need to work w/ a list
                        *GCM*)          pr_green "$default_cipher" ;;   # best ones
                        *CHACHA20*)     pr_green "$default_cipher" ;;   # best ones
                        ECDHE*AES*)    pr_yellow "$default_cipher" ;;  # it's CBC. --> lucky13

**Comment by drwetter** [comment]
Hi Peter,

Yes, it translates to RFC name TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384. That looks in fact like it's a lucky 13 cipher (AES+CBC) -- 'potentially' (http://www.isg.rhul.ac.uk/tls/Lucky13.html) vulnerable. This is the encryption part.

The attack is rater complex, that's why the risk is labeled with yellow. I said potentially because it has been probably addressed in most of the SSL stacks out there.

521 bit ECDH is one of the best key exchanges. So that's why it's in green. 

I understand that green and yellow together maybe looks like a difficult to understand thing in the output. I see no way in solving this.

Does that answer your question?

Cheers, Dirk

**Comment by drwetter** [comment]
see #193. There might be a separate test for lucky 13 potentially vulnerable ciphers

**Comment by logopk** [comment]
Hello Dirk,

Thank you for pointing me to the site of Nadhem and Kenny. It reads that openssl was patched in 2013. So in this case it should be OK to use CBC again?
Would your test of Lucky 13 provide the necessary statement and if possible remove the yellow marking? Or will it just check for CBC and mark the test failed?

The article of the two only covers CBC in open source TLS stacks. Do you know the status of IIS or Windows SChannel? Can this be checked?

Thank you and have a nice weekend.


Peter

**Comment by drwetter** [comment]
Hi Peter!

Am 09/18/2015 um 10:25 PM schrieb logopk:
> Hello Dirk,
> 
> Thank you for pointing me to the site of Nadhem and Kenny. It reads that openssl was patched in
> 2013. So in this case it should be OK to use CBC again?

If your server / client has been patched, then it should be ok for TLS 1.2 but I would suggest
to prioritze GCM suites.

> Would your test of Lucky 13 provide the necessary statement and if possible remove the yellow
> marking? Or will it just check for CBC and mark the test failed?

In order to test it "testssl.sh" would either need to check what the researchers did or at least
check whether the SSL stack has been patched -- by some means. That is beyond the scope of
testssl.sh -- but I would be happy if somebody proves me wrong and sends me a PR ;-)

So I would probably carefully phrase that the ciphers might have a potential problem.

> The article of the two only covers CBC in open source TLS stacks. Do you know the status of IIS
> or Windows SChannel? Can this be checked?

The research listed "We have not studied any closed-source implementations of TLS. " and I do not
know anybody has researched that. Only Microsoft can tell. The paper adds "Microsoft performed an
investigation and determined that the issue had been adequately addressed in previous modiﬁcations
to their TLS and DTLS implementations". Maybe some KBs make you smarter. ;-)

(Not) welcome to closed source....

> Thank you and have a nice weekend.

Thx && you too, Cheers, Dirk
