### ISSUE TITLE
[BUG] Accented characters in the certificate issuer's name results in an invalid JSON format

### ISSUE THREAD

**Issue by cygnus-xr1** [drwetter/testssl.sh#1992]
**Command line / docker command to reproduce**
- testssl.sh -oj /tmp/ [target]
- testssl.sh --json [target]

**Expected behavior**
If there are accented characters in the issuer's name (e.g. NetLock Expressz (Class C) Tanúsítványkiadó ) the resulting JSON format will be invalid.

**Your system (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS
 - Platform: Linux 5.11.0-36-generic x86_64
 - Version: 3.1dev
 - OpenSSL: openssl.Linux.x86_64

![testssl_issuer-accented](https://user-images.githubusercontent.com/91410790/134801360-58086368-783d-4827-86ef-e74415968d3f.png)

![testssl_issuer-unescaped1](https://user-images.githubusercontent.com/91410790/134801359-3c570b7b-4409-415c-b255-137f3d6281ea.png)

![testssl_issuer-unescaped2](https://user-images.githubusercontent.com/91410790/134801357-78895523-7dc5-4657-9c6f-1c748c2bf569.png)

**Comment by dcooper16** [comment]
I can repeat this error by testing www.netlock.net. It seems that OpenSSL escapes non-ASCII characters, as shown above, and JSON does not accept non-escaped '\' characters (https://www.rfc-editor.org/rfc/rfc8259.html#section-7).

I don't know whether this was intentional or not, but I see that `fileout_json_print_parameter()` outputs the value using:
```
printf "%s%s%s%s" "$spaces" "\"$parameter\"" "$filler" ": \"$value\"" >> "$JSONFILE"
```
while `fileout_csv_finding()` uses `safe_echo()`, which is `printf -- "%b" "$1"`.

It seems that using `%s` causes the string to be output unchanged, whereas `%b` results in the escape characters being interpreted, so that the UTF8 characters appear in the CSV output.

**Comment by drwetter** [comment]
Thanks for reporting, @cygnus-xr1 , and thanks @dcooper16 for identifying the culprit. See PRs


PS: 
![image](https://user-images.githubusercontent.com/8036727/135762897-e934929e-60ab-48fd-9e70-2dce5e419d9a.png)
(CC BY 2.0), Author: https://www.flickr.com/photos/acidpix/
