### ISSUE TITLE
Error report for LUCKY13 (CVE-2013-0169)

### ISSUE THREAD

**Issue by Hello-Linux** [drwetter/testssl.sh#1993]
I don't have this vulnerability. Why do I report this security problem?

LUCKY13 (CVE-2013-0169), experimental     potentially VULNERABLE, uses cipher block chaining (CBC) ciphers with TLS. Check patches

![2021-09-27 10-00-20 的屏幕截图](https://user-images.githubusercontent.com/17851645/134834822-41812505-b79f-45a5-9298-117dc9aff7e4.png)

**Comment by dcooper16** [comment]
You haven't provided enough information. The message says that the server is _potentially_ vulnerable to LUCKY13 since it offers ciphers that use CBC. If you are saying that testssl.sh is reporting that the server is potentially vulnerable even though the server does not offer any CBC ciphers, then please provide additional information as specified in https://github.com/drwetter/testssl.sh/wiki/Bug-reporting so that the issue many be investigated.
