### ISSUE TITLE
[BUG] Invalid json output if there are multiple A records and a test fails

### ISSUE THREAD

**Issue by Max7cd** [drwetter/testssl.sh#2053]
**Before you open an issue please check this repo whether this is a known problem**
Did not find it.

**Command line / docker command to reproduce**
`testssl.sh --connect-timeout 30s --openssl-timeout 30s --debug 2 --color 0 --jsonfile-pretty /tmp/result.json -p -t smtp mx02.mail.icloud.com.:25`

produced the following or a similar, faulty output multiple times:
```json
{
    "Invocation": "testssl.sh --connect-timeout 30s --openssl-timeout 30s --debug 2 --color 0 --jsonfile-pretty /tmp/result_tls_24E70B5D2838B1D4F36F711012A6C845.json -p -t smtp mx02.mail.icloud.com.:25",
    "at": "f145c430b84d:/app/testssl/bin/openssl.Linux.x86_64",
    "version": "3.1dev ",
    "openssl": "OpenSSL 1.0.2-chacha from Jan 18 17:12:17 2019",
    "startTime": "1638373575",
    "scanResult": [
        {
            "targetHost": "mx02.mail.icloud.com.",
            "ip": "17.42.251.12",
            "port": "25",
            "rDNS": "mx02.mail.icloud.com.",
            "service": "smtp",
            "pretest": [
                {
                    "id": "pre_128cipher",
                    "severity": "INFO",
                    "finding": "No 128 cipher limit bug"
                }
            ],
            "protocols": [
                {
                    "id": "SSLv2",
                    "severity": "OK",
                    "finding": "not offered"
                },
                {
                    "id": "SSLv3",
                    "severity": "OK",
                    "finding": "not offered"
                },
                {
                    "id": "TLS1",
                    "severity": "LOW",
                    "finding": "offered (deprecated)"
                },
                {
                    "id": "TLS1_1",
                    "severity": "LOW",
                    "finding": "offered (deprecated)"
                },
                {
                    "id": "TLS1_2",
                    "severity": "OK",
                    "finding": "offered"
                },
                {
                    "id": "TLS1_3",
                    "severity": "OK",
                    "finding": "offered with final"
                }
            ],
            "grease": [],
            "ciphers": [],
            "fs": [],
            "serverPreferences": [],
            "serverDefaults": [],
            "vulnerabilities": [],
            "cipherTests": [],
            "browserSimulations": [],
            "rating": []
        }
                            {
            "id": "scanProblem",
            "severity": "FATAL",
            "finding": "Couldn't connect to 17.57.152.14:25, proceeding with next IP (if any)"
        },
        {
            "id": "scanProblem",
            "severity": "FATAL",
            "finding": "repeated STARTTLS problems, giving up (2)"
        }
    ],
    "scanTime": 117
}
```

The problem is a missing comma in the json file. Unfortunately I could not identify the location of the bug in testssl.sh and I cannot reproduce it anymore.
The server I tested has behaved in multiple ways for me now and I'm not sure how to reproduce it (the above error with the bug, no error or ip blocked -> dynamic ip) 

**Expected behavior**
There should be and additional comma between the items in scanResults.

**Your system (please complete the following information):**
- OS: Manjaro Linux
- Platform: Linux 5.10.79-1-MANJARO x86_64
- Version: 3.1dev f6571c7
- OpenSSL: OpenSSL 1.0.2-chacha from Jan 18 17:12:17 2019

**Comment by dcooper16** [comment]
Hi @Max7cd,

Thanks for reporting the issue. I just submitted PR #2055, which seems to fix the issue. However, it needs more testing to make sure that it really fixes this problem and doesn't introduce a new problem.

**Comment by drwetter** [comment]
Thanks for reporting and the suggested fix, @Max7cd & @dcooper16 . Happy to merge it when it's tested so that it can be assumed it helped and has no side effects.

At the moment I have problems reproducing this. First test was with plain 3.1dev. I created an OUTPUT rule (iptables) in the middle of the scan. Second scan I seemed to be blocked by icloud. Both _jsonlint_ and _jq_ didn't have a problem with the result:


![image](https://user-images.githubusercontent.com/8036727/144591385-cb000ee6-51c8-4426-984c-9886371c1c56.png)

![image](https://user-images.githubusercontent.com/8036727/144591446-dfb82389-6a75-4c05-a1e8-b1613b77389c.png)


Maybe the trick is to drop the traffic at the right moment.

**Comment by dcooper16** [comment]
I believe that the problem is that testssl.sh assumes that the first call to `fileout()` for a target will be the one where the ID is "service." When this happens, the comma is that is needed is inserted by `fileout_json_finding()`.

```
     if "$do_pretty_json"; then
          if [[ "$1" == service ]]; then
               if [[ $SERVER_COUNTER -gt 1 ]]; then
                    echo "          ," >> "$JSONFILE"
               fi
          ...
```
In the case that was reported here, the first call to `fileout()` for the second targetHost was to report a scanProblem rather than the service and so no comma was inserted.

My PR seems to fix the problem (the indentation is wrong, but the JSON is valid). A better solution might be to keep track of whether something is the first finding for a target host rather than assuming that the "service" will be the first finding. However, if my current PR creates correct JSON and the only problem is the indentation then that's probably good enough.

The only way I've been able to test this so far has been to modify the code at the end of of testssl.sh to try a list of IPADDRs of my choosing, where the first IP address is good and the second is for a server that isn't listening on the specified port. It's not exactly the same as what @Max7cd encountered, but it has the same problem.
