### ISSUE TITLE
Improve BEAST check

### ISSUE THREAD

**Issue by drwetter** [drwetter/testssl.sh#208]
1) still there are some CBC ciphers missing, testssl.sh -x CBC with mapping file will tell (not your fault)
2) for speed improvements it would not hurt to add 1-2 calls per protocol in the beginning. If those fail the remaining 228 (114*2) ciphers don't have to be tested
3) color should be changed to yellow if TLS 1.1 or TLS 1.2 is offered as this mitigates BEAST. In any case: It's a client issue. The test only lines out a potential problem on the client side

see also #207

**Comment by drwetter** [comment]
2+3 will be off the table with the next commit

**Comment by typingArtist** [comment]
1) oh, hmm … let’s see. I was already about to improve the script in the directions you mentioned (not to check TLS 1.2 ciphers), but I will take a look at missing CBC ciphers.
2) Do you mean, first try to set up connections with multiple collections of entries from cbc_cipher_list to check whether any of these could be connected with?
3) Well … I don’t want to go into deep philosophical discussions here, but I would not call TLS1.1/TLS1.2 support a BEAST mitigation, as BEAST is not mitigated at all for older clients. So I’m not green with, e.g. Qualys’ statement https://community.qualys.com/blogs/securitylabs/2013/09/10/is-beast-still-a-threat. The only real mitigation is or would be to disable anything below TLS 1.2, but that would leave too many clients offline. I’d call their position paper about BEAST a political statement, at best, because they’d actually give most servers in the world at least a C, better an F for still supporting TLS 1.0 with either RC4 or BEAST active. This would either render a lot of sites unreachable which care for the SSL Labs grade, or it would become en vogue to live by a C or F grade. Finally remember, there’s not just https and its clients – SMTP with STARTTLS is still a big mess with a lot of MTAs in very bad condition – old, full of security holes and un-maintained on the setup side. But since this issue is not visible to the user, it flies way below the radar and is not tackled in the right way.

**Comment by drwetter** [comment]
WRT 3) I agree to your concern but as you said it's not practical to lock out any client whcih speak TLS 1.2. 

STARTTLS is not secure in the first place as the encryption is most of the time not enforced. But agreed, it's a mess also in my testing experience. Mainly because the default setups of mail servers aren't as good as for Apache or nginx. 

Nobody cares about proper encryption when it comes to mail but that's another topic....
