### ISSUE TITLE
doesn't seem to be a TLS/SSL enabled server....but site comes up fine in browsers

### ISSUE THREAD

**Issue by tonyguadagno** [drwetter/testssl.sh#2116]
hi, when i run your script against my site...tickets.fujifilmusa.com:443 i get this
```
172.19.5.46:443 doesn't seem to be a TLS/SSL enabled server
 The results might look ok but they could be nonsense. Really proceed ? ("yes" to continue) --> yes
 Service detected:       Couldn't determine what's running on port 443, assuming no HTTP service => skipping all HTTP checks


 Testing protocols via sockets except NPN+ALPN

 SSLv2      not offered (OK)
 SSLv3      not offered (OK)
 TLS 1      not offered
 TLS 1.1    not offered
 TLS 1.2    not offered
 TLS 1.3    not offered

```

however the site comes up fine in all browsers....also, i found this other testing script ([https://github.com/rbsec/sslscan/](https://github.com/rbsec/sslscan/)) and it reports the site as fine.

so, is there a problem with my site or with the script?

thanks for your efforts on this!

**Comment by drwetter** [comment]
Hi @tonyguadagno,

thanks for reporting. It's a bug by our script.

Stay tuned.

Cheers, Dirk

**Comment by tonyguadagno** [comment]
h, no problem...btw, [SSLLabs](https://www.ssllabs.com) is also choking on the site....so i am not ruling out a bad config on my side...but i am just not seeing what i might be doing wrong.
if you see anything wrong on my site, please let me know
thanks

**Comment by drwetter** [comment]
``openssl s_client -tls1_2 -connect tickets.fujifilmusa.com:443`` works. We do some handshakes in sockets (i.e. w/o openssl) before. Those fail, returning a TLS alert.

Maybe @dcooper16 can shed some light in this?

**Comment by dcooper16** [comment]
Hi @tonyguadagno, @drwetter,

I believe that I discovered the issue. It seems that tickets.fujifilmusa.com only works if the Signature Algorithms extension includes the recently-defined RSA-PSS algorithms. At the moment, testssl.sh only includes these algorithms in a TLS 1.3 ClientHello. It seems, however, that OpenSSL includes them in a TLS 1.2 ClientHello, so I guess it's okay for us to modify testssl.sh to also include them in the TLS 1.2 and below ClientHello.

Note that while OpenSSL 1.1.1 does include the RSA-PSS algorithms in the Signature Algorithms extension, OpenSSL 1.0.2 does not. So, even after testssl.sh has been updated to offer the RSA-PSS algorithms, testing tickets.fujifilmusa.com will require using the `--openssl=` option to specify a newer OpenSSL binary.

While many browsers will work with tickets.fujifilmusa.com, testssl.sh's client simulations shows that many will not, and my guess would be that this is because of tickets.fujifilmusa.com only accepting RSA-PSS.

**Comment by drwetter** [comment]
Thanks, David for your quick response and your PR. Much appreciated! Will merge that when the Ci run is finished.

> Note that while OpenSSL 1.1.1 does include the RSA-PSS algorithms in the Signature Algorithms extension, OpenSSL 1.0.2 does not. So, even after testssl.sh has been updated to offer the RSA-PSS algorithms, testing tickets.fujifilmusa.com will require using the --openssl= option to specify a newer OpenSSL binary.

you're right. Maybe some voodoo upfront would help here to tell which binary to use -- the old one or /usr/bin/openssl which is often openssl >= 1.1.0. I did a similar thing for STARTTLS injection.

I wonder though what the best approach would be: a connect with the supplied openssl, if it fails use /usr/bin/openssl when openssl >= 1.1.1?  That might also help for TLS 1.3 only hosts and would still work for deprecated hosts (SSLv2 / SSLv3 only). Just some thoughts...

**Comment by drwetter** [comment]
HI @tonyguadagno ,

please update and try again, best with ``--openssl=/usr/bin/openssl``

Cheers, Dirk

**Comment by dcooper16** [comment]
Hi @tonyguadagno,

I found another issue this morning with testing tickets.fujifilmusa.com (see #2120).
