### ISSUE TITLE
[BUG / possible BUG] Incorrect PFS output on servers with only brainpool elliptic curves

### ISSUE THREAD

**Issue by Phil2407** [drwetter/testssl.sh#2131]
If a server only accepts brainpool curves (e.g. via "SSLOpenSSLConfCmd Curves brainpoolP256r1" in an Apache2 vhost definition), testssl will say "No ciphers supporting Forward Secrecy offered" when checking for PFS (i.e. testsssl -f) even though PFS ciphers are available and "openssl s_client -connect ip:port -curves brainpoolP256r1 -tls1_2" is able to connect using those ciphers.
Also running with "--ssl-native" provides the correct output.
I only tested this on local installations so unfortunately there is no target IP I could provide.

**Command line / docker command to reproduce**
testssl -f ip:port

**Expected behavior**
Testssl should list all suported PFS ciphers with elliptic curve brainpoolP256r1

 - OS: Kali GNU/Linux Rolling
 - Platform: Linux 5.14.0-kali4-amd64 x86_64
 - Version: testssl 3.0.7 from https://testssl.sh/

**Additional context**
I did a bit of debugging myself and to me it seems like there is a logic issue in run_pfs().
In line 9627 (this is version 3.0.7) there is a check if tls 1.3 is offered. If not, tls_sockets is called with version "04" which I understand is tls1.3 again. I changed this value to "03" in a local copy and got the expected result. I'm not sure though if that is actually the solution or if I just broke several other use cases by doing this.

**Comment by drwetter** [comment]
Ok, thanks!

Did you try 3.1dev? And is that possible to share the hostname (privately:``grep SWCONTACT testssl.sh``)

**Comment by Phil2407** [comment]
Yes, I am getting the exact same results on 3.1dev.
I am only testing on local VM at the moment so there is no hostname to share I guess (at least none of any help).
If there is anything else I can provide to help reproduce this (apache site conf, or something like this) let me know

**Comment by drwetter** [comment]
Thx, getting a rough idea of the config  would be great.

**Comment by Phil2407** [comment]
So the server is a VM running ubuntu server 20.04.4 LTS with an apache2 http server. The following vhost config was used to find this behaviour:
```
<IfModule mod_ssl.c>
	<VirtualHost _default_:4435>
		ServerAdmin webmaster@localhost
		DocumentRoot /var/www/html
		ErrorLog ${APACHE_LOG_DIR}/error.log
		CustomLog ${APACHE_LOG_DIR}/access.log combined
		SSLEngine on
		SSLOpenSSLConfCmd Curves brainpoolP256r1
		SSLCertificateFile	/opt/ECC/Brainpool/brainpool.crt
		SSLCertificateKeyFile /opt/ECC/Brainpool/brainpool.key
		SSLProtocol TLSv1.2
		SSLCipherSuite HIGH
		<FilesMatch "\.(cgi|shtml|phtml|php)$">
				SSLOptions +StdEnvVars
		</FilesMatch>
		<Directory /usr/lib/cgi-bin>
				SSLOptions +StdEnvVars
		</Directory>
	</VirtualHost>
</IfModule>
```
brainpool.crt is a self-signed certificate over the elliptic curve brainpoolP256r1

**Comment by drwetter** [comment]
--> next week hopefully

**Comment by dcooper16** [comment]
I just tried this and was able to repeat the issue. The problem occurs around the line that you mentioned, but the proposed solution isn't the correct one.

Under normal circumstances calling `tls_sockets()` with "04" instead of "03" would not be a problem. A TLS 1.2 server will accept a TLS 1.2 ClientHello and respond by negotiating TLS 1.2. The issue here is that RFC 8446 (TLS 1.3) removed all but a few curves from the supported_groups extension (any curves that were considered weak or that didn't appear to be in use were removed). By default, the ClientHello sent by `tls_sockets()` only sends the curves allowed by RFC 8446 in a TLS 1.3 ClientHello, but it includes all previously defined curves in a TLS 1.2 or earlier ClientHello.

The same things happens with OpenSSL 1.1.1. Sending a TLS 1.3 ClientHello (i.e., by not specifying a protocol version to the s_client command) will result in a failure to connect to this server, but sending a TLS 1.3 ClientHello (e.g., by including the `-no_tls1_3` flag) will result in a successful connection. For this reason, running testssl.sh in `--ssl-native` mode with `--openssl=<OpenSSL 1.1.1 binary>` will produce the same error.

At the moment, I think the best solution would be to try a TLS 1.2 ClientHello if the TLS 1.3 ClientHello fails, but I'll have to thin about it a bit more.
