### ISSUE TITLE
[BUG / possible BUG] --show-each with -E causes Overall Grade F due to weak cipher suites, despite those cipher suites not being available remotely

### ISSUE THREAD

**Issue by bjorn-wiberg** [drwetter/testssl.sh#2203]
It appears that adding --show-each to -E causes the Overall Grade to be capped to F, despite those weak cipher suites not being available remotely (`not a/v`).

The rating says:

```
 Rating (experimental)

 Rating specs (not complete)  SSL Labs's 'SSL Server Rating Guide' (version 2009q from 2020-01-30)
 Specification documentation  https://github.com/ssllabs/research/wiki/SSL-Server-Rating-Guide
 Protocol Support (weighted)  0 (0)
 Key Exchange     (weighted)  0 (0)
 Cipher Strength  (weighted)  0 (0)
 Final Score                  0
 Overall Grade                F
 Grade cap reasons            Grade capped to F. Using cipher suites weaker than 112 bits
                              Grade capped to A. HSTS is not offered
```

It is as if the mere displaying of the weak cipher suites being tested causes the grade to be capped to F.

**Command line / docker command to reproduce**

```
# yields Overall Grade: A
./testssl.sh -E -9 scbbs.nsupdate.info:443

# yields Overall Grade: F
./testssl.sh -E -9 --show-each scbbs.nsupdate.info:443
```

**Expected behavior**
The grade should not be capped to F; both command lines should yield the same grade (A).

**Your system (please complete the following information):**
 - OS: `Debian GNU/Linux 11 (bullseye)`
 - Platform: `Linux 5.10.0-16-amd64 x86_64`
 - Version: ```
    testssl.sh       3.1dev from https://testssl.sh/dev/
    (88e80d2 2022-07-02 22:13:06)```
 - Version if running from git repo: `commit 88e80d26881c4f73700f729a518ee33cde616307` 
 - OpenSSL: `./bin/openssl.Linux.x86_64`

**Comment by dcooper16** [comment]
Hi @bjorn-wiberg,

Thanks for reporting. I am not very familiar with the code for creating ratings, but it seems that the rating is based on the cipher suites that are displayed, whether they are supported or not.

In particular, the function `neat_list()` is used to display ciphers in individual rows. It seems that `neat_list()` calls `set_ciph_str_score()` for every cipher, whether it is supported by the server or not. In most cases, this is okay, since usually only supported ciphers are printed.

Fortunately, it seems that the fix should be easy, since the 6th argument to `neat_list()` seems to indicate whether the cipher being printed is actually supported by the server.

I don't have time to try to fix this at the moment. However, I may have some time in a few weeks, if no one else has fixed it before then.

**Comment by bjorn-wiberg** [comment]
Thank you, @dcooper16! It is much appreciated!

**Comment by drwetter** [comment]
Thanks for the bug report. Can reproduce it.

Give me a bit to look into it, just returned from vacation.

**Comment by drwetter** [comment]
PR pending.

Thanks for the hint, @dcooper16 . I had first a bit of a problem understanding the variable you mentioned as the inline documentation indicated a boolean.

**Comment by dcooper16** [comment]
Hi Dirk,

It seems that PR #2207 does not fix this bug. I tried it on testssl.sh and got different results depending on whether or not the `--show-each` flag was used.

I believe there was a misunderstanding of the code. The 6th argument to `neat_list()` is always true, false, or empty. The strings "available" or "not a/v" are provided to `fileout()` _after_ the output of `neat_list()`, but these strings are not passed to `neat_list()`.

`neat_list()` is called with an empty 6th argument in two cases: (1) when the cipher hasn't been tested and (2) to provide a string to `fileout()` after `neat_list()` has already been called to print the cipher information to the terminal. So, there is no need to call `set_ciph_str_score()` when $how2show is empty. Simply calling `set_ciph_str_score()` whenever $how2show is true results in `set_ciph_str_score()` being called whenever `neat_list()` is called with a cipher that is known to be supported by the server.
