### ISSUE TITLE
Batch mode and "appears to support TLS 1.3 ONLY. You better use --openssl=<path_to_openssl_supporting_TLS_1.3>" error

### ISSUE THREAD

**Issue by huornlmj** [drwetter/testssl.sh#2358]
**Before you open an issue please check which version you are running and whether it is the latest in stable / dev branch**
I am running version from Docker hub drwetter/testssl.sh:latest

When running testssl in batch mode (e.g. with the --file for input), if I scan an endpoint that only supports TLS 1.3, I get the error:

```console
{host} appears to support TLS 1.3 ONLY. You better use --openssl=<path_to_openssl_supporting_TLS_1.3>
```

How do I overcome this in batch mode?

**Expected behavior**

**Your system (please complete the following information):**
 - OS: Ubuntu 22.04.2 LTS
 - OpenSSL: `/home/testssl/bin/openssl.Linux.x86_64`

**Comment by huornlmj** [comment]
BTW - I tried using the `--warnings off` option but it gets overridden by the `--file` option.

**Comment by drwetter** [comment]
Hi @huornlmj ,

the output is a hard recommendation. It has the important reason that you miss otherwise parts of the tests -- like HTTP headers. That's why we don't give users the possibilty to squash this recommendation other than indicated.

I would recommend in general to consider  ``--openssl=/usr/bin/openssl `` . Unless you have <= SSLv3 only hosts.

In future versions we'll plan for those border cases to always use  the right(TM) openssl.
