### ISSUE TITLE
homepage testssl.sh - certificate expired

### ISSUE THREAD

**Issue by patrick-othmer** [drwetter/testssl.sh#2593]
The website certificate has expired.

![Bildschirmfoto_2024-10-31_11-21-57](https://github.com/user-attachments/assets/7fb033f8-0be0-49b2-bdd5-94f60cb9e9b0)

**Comment by drwetter** [comment]
Yeah, thanks. Realized that too. Should not tamper with things when I am too tired.

Will be done by EOD when I am no longer afk


-------- Ursprüngliche Nachricht --------
Von: Patrick Othmer ***@***.***>
Gesendet: 31. Oktober 2024 11:22:41 MEZ
An: "drwetter/testssl.sh" ***@***.***>
CC: Subscribed ***@***.***>
Betreff: [drwetter/testssl.sh] homepage testssl.sh - certificate expired (Issue #2593)

The website certificate has expired.

![Bildschirmfoto_2024-10-31_11-21-57](https://github.com/user-attachments/assets/7fb033f8-0be0-49b2-bdd5-94f60cb9e9b0)



-- 
Reply to this email directly or view it on GitHub:
https://github.com/drwetter/testssl.sh/issues/2593
You are receiving this because you are subscribed to this thread.

Message ID: ***@***.***>

-- 
Sent from my mobile. Apologize for my brevity and typos/autocorrection
