### ISSUE TITLE
Proxy and openssl version interoperability

### ISSUE THREAD

**Issue by istipovic** [drwetter/testssl.sh#309]
Hi,

tried to use testssl.sh (version 2.6) with --proxy option (I setup Burp as a proxy). 

However the problem seemed to be the openssl version as the error displayed was "Fatal error : your openssl is too old to support proxy option"

I was using openssl 1.0.1k initially and after the error upgraded it to 1.0.2g. 

1.0.2g is the latest stable openssl version which still caused the same error message.

I understand testssl.sh website refers to 1.0.2e but it surely does not support only one version of openssl - or does it?

What versions of openssl are/should be supported and is this behavior a bug?

Thanks

Regards

**Comment by drwetter** [comment]
Hi @istipovic,

what does ``openssl s_client -help 2>&1 | grep -w proxy`` say? Be sure that the right openssl version is being picked up. Don't know where you got your openssl version from and how it was compiled, best is always to use the one from github or my web site ( https://testssl.sh/openssl-1.0.2e-chacha.pm.ipv6.Linux.tar.gz).:

``As for security reasons some distributors outphase the dirty stuff you want to check for – it's recommended to compile OpenSSL (best from github.com/PeterMosmans/openssl) by yourself or check out the distributed OpenSSL binaries (Linux) – they come with a whopping 195 ciphers – ~80 more than on an average Linux distro (note: openssl-1.0.2e-chacha.pm.ipv6.Linux.tar.gz is a Linux-only tarball with IPv6 support. openssl-1.0.2e-chacha.pm.tar.gz contains also FreeBSD and Darwin Binaries). In any case: Except the ciphers, you will get a warning if your OpenSSL client cannot perform a specific check, see below. Since 2.4 on some of those checks are done with bash sockets – to be improved gradually. Same applies to LibreSSL: Basically it has lots of flawed features (ciphers, protocols and more) for security reasons disabled – thus for security testing it's not a good choice.``

BTW: 2.6 is considered stable but it's old and lacks features (not as far as the proxy is concerned though).


HTH, Dirk

**Comment by istipovic** [comment]
openssl s_client -help 2>&1 | grep -w proxy returns nothing.

I downloaded my version of openssl from openssl.org, last stable version as they indicated, 1.0.2g http://openssl.org/source/openssl-1.0.2g.tar.gz and used ./configure, make, make install (maybe ./configure required some flags for proxy support?).

I guess I should download and compile openssl 1.0.2e you suggest -is there any special flag for compiler to enable proxy support

Thanks a lot

**Comment by drwetter** [comment]
https://github.com/drwetter/testssl.sh/tree/master/bin

**Comment by drwetter** [comment]
closing this. HTH..

**Comment by malek0512** [comment]
Hello,

I have the same problem. Has a solution been found?

Thanks in advance.

**Comment by drwetter** [comment]
yes @malek0512. Use an openssl version which supports proxying. ``openssl s_client -help 2>&1 | grep -w proxy`` will tell you. Most recent do.

Also the version supplied here should work.
