### ISSUE TITLE
Output JSON/HTML

### ISSUE THREAD

**Issue by drwetter** [drwetter/testssl.sh#31]
Json / html would be fine. Target: version 2.2.

**Comment by jonorossi** [comment]
@drwetter have you put any thought into how you'd like the implementation to work?

I see two real options here since testssl.sh is written in bash and not a language with a JSON library. Either append to a handcrafted JSON variable as the script runs paired with each existing print to stdout, or perform in-place JSON modification using a CLI tool like [json](http://trentm.com/json/) that you'd add new attributes as you went.

I've had a skim read through the whole script file and it feels like there should be a bit more structure around the scan results, which would allow the implementation of ratings (#100) to be a little more formal like ssllabs. However, I'm not a bash master and don't even know if bash can do what I'm thinking.

**Comment by jonorossi** [comment]
I just found [json-bash](https://github.com/ingydotnet/json-bash), which can do things like the json CLI tool I just mentioned, however this is a single bash script rather than a node.js script. The way it allows you to represent the JSON structure in a path syntax with a value should make it pretty easy to implement.

**Comment by drwetter** [comment]
Am 07/21/2015 um 08:02 AM schrieb Jonathon Rossi:
> @drwetter <https://github.com/drwetter> have you put any thought into how you'd like the
> implementation to work?

a bit. I was up to now more on the user side and was planning to see who other were
doing this.

> I see two real options here since testssl.sh is written in bash and not a language with a JSON
> library. Either append to a handcrafted JSON variable as the script runs paired with each
> existing print to stdout, or perform in-place JSON modification using a CLI tool like json
> <http://trentm.com/json/> that you'd add new attributes as you went.

The latter need node.js. That makes testssl.sh too depended.

I am more in favor of the first suggestion. Roughly I was thinking on first extending the output
functions. But any output I am generating so far is for humans to read and not really adaptable
to JSON. Then the idea was to just have another output function. This one would add each check
a JavaScript object.

That sounded to me like the easiest thing, road might be a bit steep though in the beginning.

> I've had a skim read through the whole script file and it feels like there should be a bit more
> structure around the scan results, which would allow the implementation of ratings (#100
> <https://github.com/drwetter/testssl.sh/issues/100>) to be a little more formal like ssllabs.

That's somewhere planned on the road, yes.

> However, I'm not a bash master and don't even know if bash can do what I'm thinking.

Well, in software development almost everything is possible. Just a matter of will
and complexity. ;-) If you think about it before doing that might be not too
difficult. Here are my thoughts.

For the rating I guess the best is a global variable. It starts with hundred (equals
100%) and then each step comes a penalty. So far so good. The difficult part is a fair
rating. If you look at SSLlabs: they have a 10 page PDF for this. So one needs to put "some"
thoughts into it. And: it's changing over time as new bugs hit the streets or it becomes
public e.g. that EC curve ABC is compromised or whatever.

That's for me way ahead, as now other points are more important. But I don't want to hold
others back...

Cheers, Dirk

**Comment by drwetter** [comment]
Am 07/21/2015 um 08:11 AM schrieb Jonathon Rossi:
> I just found json-bash <https://github.com/ingydotnet/json-bash>, which can do things like the
> json CLI tool I just mentioned, however this is a single bash script rather than a node.js
> script. The way it allows you to represent the JSON structure in a path syntax with a value
> should make it pretty easy to implement.

doesn't look so bad.

License is not clear though and the fact whether it conflicts with the one of testssl.sh .
Also testssl.sh doesn't need a parser/dumper, just an output function is needed which
does the brackets, commas and key-values. KISS.

Cheers, Dirk

**Comment by jpluimers** [comment]
On a system that has enough binaries, I'd go this way:

1. Build the test result in JSON or XML
2. Transform the JSON or XML to final output: coloured console, plain text, HTML, XML or JSON

But testssl.sh is a bash script, so you'd probably want bash scripts supporting JSON or XML. Or provide JSON or XML binaries for each and every platform you support.

Since I'm much more of an XML than a JSON person and given there - unlike XML transformation languages/tools like XSLT - is [no good JSON transformer outside the Java and Node.js worlds][1], I'd go for XML: 

If you confine to a subset of XML (which given the output, I think it is not really hard), then you could even use an XML subset as writing XML is easy and parsing is less easy (in a lesser extent, that holds for JSON as well although confining a JSON subset is a lot harder).

A subset could be like this: only elements, only UTF-8, no comments, no attributes, no CDATA, very limited element depth (so you need to design a good data model first).

There are enough examples of [simple rdom based bash XML parsers][2] like [Parse_XML][3] with [good examples][4] on how to use them or [how they work][5]. I found even [one parsing elements and attributes][6] (:

If you can provide binaries, then go the [XSLT 1.0 way][7] or [`xmllint` way][8].

Many systems include xmllint/[xsltproc binaries][9] ([for instance even older Mac OS X versions doe][10]). But then you'd need to set baseline requirements.


  [1]: http://stackoverflow.com/questions/1618038/xslt-equivalent-for-json
  [2]: https://www.google.com/search?q=%22rdom%22%20bash%20xml
  [3]: http://www.schnallich.net/index.php/Bash/Parse_XML
  [4]: https://searchcode.com/codesearch/view/1943063/
  [5]: http://stackoverflow.com/questions/893585/how-to-parse-xml-in-bash
  [6]: http://www.humbug.in/2010/parse-simple-xml-files-using-bash-extract-name-value-pairs-and-attributes/
  [7]: https://www.google.com/search?q=xslt%201.0%20linux
  [8]: http://unix.stackexchange.com/questions/83385/parse-xml-to-get-node-value-in-bash-script
  [9]: https://www.google.com/search?q=xsltproc%20binaries
  [10]: http://www.explain.com.au/oss/libxml2xslt.html

**Comment by drwetter** [comment]
Momentarily I love still the KISS and beautiful approach, i.e. another output function which completes step by step the  json representation. Other binaries makes the thing too fat, depended or ugly, given the fact that there's cool socket stuff in testssl.sh as well.

**Comment by drwetter** [comment]
HTML is the only thing which is open. Question is whether it should be done by testssl.sh itself.

**Comment by seccubus** [comment]
Since we have #268 what would we need for this? A simple HTML file output?

**Comment by drwetter** [comment]
yes, I originally thought so. But as we have ``aha`` and there wasn't a strong suggestion why we want to have a native implementation we should close this.

**Comment by jpluimers** [comment]
What's `aha`?

**Comment by drwetter** [comment]
Am 5. Juli 2016 21:09:20 MESZ, schrieb Jeroen Wiert Pluimers <notifications@github.com>:
>What's `aha`?


ANSI HTML adapter, see --help. Isn't that included in home brew?

Cheers, Dirk

-- 
Set from my mobile. Excuse my brevity&typos

**Comment by jpluimers** [comment]
@drwetter duh: I never noticed testssl made it to home brew (:

**Comment by jpluimers** [comment]
In case anyone want clickable `URI`s in the `html` output generated by `aha`, please test the `perl` replacement `regex` I posted at https://github.com/theZiz/aha/issues/20#issuecomment-249370480 as I'm anxious to see how well (or bad) that works. If it fails, please post a comment there.
