### ISSUE TITLE
potential false positives on CCS and heartbleed @ slow connections

### ISSUE THREAD

**Issue by drwetter** [drwetter/testssl.sh#313]
which seem to happen on very slow connections (satellite or vpn). Sometimes non-reproducible results. (reported privately to me)

**Comment by drwetter** [comment]
Needs to be addressed but as it happens seldom this won't happen (by me) for the upcoming 2.8 release

**Comment by fishouttah20** [comment]
This issue seems to be compounded by using parallel with a large list of domains and 2.9dev. Out of a list of 3500 domains, 60 came back with Heartbleed which I believe all but one are false positives. (based on SSLLabs scans) I spot checked a few, one at a time on the same Ubuntu 16.04 instance and when checked individually I've been unable to get them to show up as vulnerable. They all show as Not Vulnerable (Timeout).

**Comment by drwetter** [comment]
ok, got that but with that sparse information it's hard to guess. First guess though: The file handle -- depends what you mean by parallel.

Only FP for heartbleed and not CCS?

**Comment by fishouttah20** [comment]
I ran 16 sessions in parallel on an 8 core system so wasn't trying to do them all at the same time. 10 of the 60 sites returned a finding for CCS but I'll need to confirm which were false positives, regardless, all 60 didn't have CCS. 

I re-ran the scan against just the 60 sites but none of them triggered a Heartbleed detection on the rescan. I'll try to compile more details.

**Comment by drwetter** [comment]
see a22e4e5228228f9188cf6ab221b8f1f1a5b969c7.

Should address all heartbleed FP -- single threaded at least. CCS will be tackled as soon at the host I had for testing is up again
