### ISSUE TITLE
Check for MS14-066 / CVE-2014-6321

### ISSUE THREAD

**Issue by drwetter** [drwetter/testssl.sh#331]
... aka Winshock.

Preferably use something better than check for four ciphers and TLS 1.2.

**Comment by drwetter** [comment]
Hi,

thx to Sebastian (hello!) I compiled a version of openssl which potentially can trigger this bug -- according to http://www.securitysift.com/exploiting-ms14-066-cve-2014-6321-aka-winshock/  , See https://testssl.sh/openssl-ms14-066.Linux.x86_64 .

ATM I can't test it as I don't have a potentially vulnerable machine handy. Also the test would kill lsass,exe, so it's not easy to test. Anybody can help here with a private machine ? (further instructions, see blog above).

Another non-invasive way might be like Nessus is doing it. In the plugin dir there's is a file=blob named ms14-066.nbin . I am not suggesting to copy it but Nessus seems to have a less intrusive way of checking this vulnerability.  Any idea how that could work?

Cheers, Dirk

**Comment by drwetter** [comment]
See also Canvas tool: http://www.theregister.co.uk/2014/11/17/ms_schannel_crypto_poc/

**Comment by drwetter** [comment]
Another piece of information: http://researchcenter.paloaltonetworks.com/2014/12/code-trigger-ms14-066-ecdsa-server-bof-vulnerability/

**Comment by VoidSec** [comment]
@drwetter I'm currently working on it! I've vulnerable Windows 7 x86 and x64 machines. I tried your compiled OpenSSL version but I'm unable to crash lssas nor to hit the breakpoint. Would you mind sending me the source? I'll recompile it from scratch.

**Comment by drwetter** [comment]
Hi @VoidSec, that sounds cool!

I have the source on a machine I currently have limited access to. That'll take a bit. Please ping me if I forget this. 

Or, @ Sebastian: Are you listening?

**Comment by VoidSec** [comment]
Sure, I'll ping you in a week. Regarding Nessus (I'm also working on understanding how they made the detection) plugins appears to be PID:79127

**Comment by drwetter** [comment]
Good would be also a packet capture of the NSE plugin's ClientHello, maybe side by side by a regular TLS ClientHello of Nessus

**Comment by drwetter** [comment]
Found the diff which was sent to me in my mail, see here:


[ms14-66.diff.txt](https://github.com/drwetter/testssl.sh/files/3413447/ms14-66.diff.txt)

**Comment by VoidSec** [comment]
I've recovered the right OpenSSL version on which the diff is based of; made changes in order to define setChar function and some other variables but I'm still not able to hit the crash. @drwetter that's all you have?

Anyway, I've approached it from another POV. It seems that the patch for ms14-066 introduced 3/4 new cyphers. We should be able to detect those cyphers and consider the host patched if it has support. I'm still testing it on w7/win server but tomorrow I should be able to post more info.

**Comment by drwetter** [comment]
Yes, that's all.

The cipher method is probably not the right thing to do as it leads to false positives.

The nessus method was reliable. I had that once in a consulting 'gig' where the windows guys insisted that was a false positive as all patches were applied according to SCCM but in fact SP1 was missing...

IIRC that was unauthenticated scan over the network.

**Comment by VoidSec** [comment]
Yep, it leads to false positives because the OS version should be checked too as appears that for Windows Server 2012 some of the ciphers were already present.

Leaving the cyphers list here as a reference:
- DHE-RSA-AES256-GCM-SHA384
- DHE-RSA-AES128-GCM-SHA256
- AES256-GCM-SHA384
- AES128-GCM-SHA256

I'll switch back on the nessus method

**Comment by VoidSec** [comment]
I finally had time to perform some checks. I’ve enabled Nessus PID 79638  and changed the port configuration until the plugin was not anymore able to perform the check. 
I’ve started with port 80,139,443,445 and 3389 and firewalled one by one.
Minimum configuration for the Plugin to works is port 443 IIS or 3389 RDP.
I can confirm that PID 79638 only checks for cyphers.

> Note that this plugin sends a client Certificate TLS handshake message followed by a CertificateVerify message. 

I'm now trying filtering out cyphers in order to detect the minimum checks needed

**Comment by drwetter** [comment]
> I can confirm that PID 79638 only checks for cyphers.

how can you tell? That plugin ("uncredentialed check") seems to be a binary (--> ms14-066.nbin) not a NASL script (https://www.tenable.com/plugins/nessus/79638). 

> Because if you do not like to use cyphers method to check for this vuln I do not have any more ideas.

as said above: Look into the ClientHello(s) when running the plugin against the server.

C**i**phers only (s/y/**i**/) is prone to false positive and will be _at best_ included when running experimental flag (``EXPERIMENTAL=true ./testssl.sh ...``). But I rather would not do that. Also there might be false negatives as using the registry one can change ciphers on windows.

**Comment by drwetter** [comment]
To conclude for the future the discussion:

The detection via what Nessus does is probably the best choice. Other sources I found today are similar:patch sources, often create a certificate, run it (some (securitysift: RDP doesn't work) -- then crash the server.

Crashing is not what we want. We want to detect the flaw.

**Comment by VoidSec** [comment]
79638 is a binary indeed, is just that I've sniffed the entire traffic between the two hosts and since it's uncredentialed I was able to narrow it down at the sole TLS traffic.

I have many "client hello" to check in my traffic but at the end the dection will be, for sure, a mix of cyphers and some obscure value retrieved by the TLS connection that Nessus use to check for ms14-066.
I can also assure that RDP works too: https://www.malwaretech.com/2014/11/how-ms14-066-winshock-is-worse-than.html

> It was even the same story with remote desktop (RDP), a protocol that doesn’t even support client certificates, I was still able to trigger a breakpoint.

Crashing of course wasn't taken into consideration as detection mechanism ;)

**Comment by drwetter** [comment]
A while ago I thought I should close this as it is not longer relevant, But I actually encountered a potential vulnerable server.

I almost missed that one so I think it's reasonable to add a warning when the ciphers are not available and the server banner is either IIS 8.0 or (weaker) IIS 8.5. 

For RDP is there a banner or something which provides a second criteria as for the webserver?

**Comment by drwetter** [comment]
@VoidSec see  #1718. 

I encountered such a server recently -- unfortunately. If you have more solid methods than securitysift or one which does not even kill lsass,exe I would be happy if you could let me know. (``grep SWCONTACT testssl.sh``)

**Comment by drwetter** [comment]
closed via https://github.com/drwetter/testssl.sh/commit/edf669711fd060b081263e005cbb65ee66358d69
