### ISSUE TITLE
No protocol detected

### ISSUE THREAD

**Issue by matteocorti** [drwetter/testssl.sh#350]
If I test appweb7202.ethz.ch I get

```
 Testing protocols (via sockets except TLS 1.2, SPDY+HTTP2) 

 SSLv2      not offered (OK)
 SSLv3      not offered (OK)
 TLS 1      not offered
 TLS 1.1    not offered
 TLS 1.2    not offered (NOT ok)
 SPDY/NPN   not offered
 HTTP2/ALPN not offered
```

No protocol is supported. But then

```
 Testing server preferences 

 Has server cipher order?     yes (OK)
 Negotiated protocol          TLSv1
 Negotiated cipher            ECDHE-RSA-AES256-SHA, 521 bit ECDH
 Cipher order
     TLSv1:     ECDHE-RSA-AES256-SHA 
```

It seems that the protocol test is not able to detect TLS 1 (which is the only one supported by this server)

**Comment by dcooper16** [comment]
The problem here seems to be with the server, but I can't figure out exactly what the problem is. Using the "--ssl-native" native option seems to produce better results, but whether a test succeeds or fails seems to depend on the exact list of cipher suites that are included in the ClientHello. For example, the following command works using the current development version of testssl.sh:

`bash github/testssl_20160510.sh --openssl=mygitfork/testssl.sh/bin/openssl.Linux.x86_64-krb5 --debug 5 --devel 01 "c0,0a,00,39,00,38,00,37,00,36,00,88,00,87,00,86,00,85,c0,0f,c0,05,00,35,00,84,00,95,c0,13,c0,09,00,33,00,32,00,31,00,30,00,9a,00,99,00,98,00,97,00,45,00,44,00,43,00,42,c0,0e,c0,04,00,2f,00,96,00,41,00,07,00,94,c0,11,c0,07,00,66,c0,0c,c0,02,00,05,00,04,00,92,c0,12,c0,08,00,16,00,13,00,10,00,0d,c0,0d,c0,03,00,0a,00,93,00,15,00,12,00,0f,00,0c,00,09,00,62,00,09,00,65,00,64,00,14,00,11,00,0e,00,0b,00,08,00,ff" appweb7202.ethz.ch`

However, adding one more cipher suite (as follows) to the list causes it to fail:

`bash github/testssl_20160510.sh --openssl=mygitfork/testssl.sh/bin/openssl.Linux.x86_64-krb5 --debug 5 --devel 01 "c0,0a,00,39,00,38,00,37,00,36,00,88,00,87,00,86,00,85,c0,0f,c0,05,00,35,00,84,00,95,c0,13,c0,09,00,33,00,32,00,31,00,30,00,9a,00,99,00,98,00,97,00,45,00,44,00,43,00,42,c0,0e,c0,04,00,2f,00,96,00,41,00,07,00,94,c0,11,c0,07,00,66,c0,0c,c0,02,00,05,00,04,00,92,c0,12,c0,08,00,16,00,13,00,10,00,0d,c0,0d,c0,03,00,0a,00,93,00,15,00,12,00,0f,00,0c,00,09,00,62,00,09,00,65,00,64,00,14,00,11,00,0e,00,0b,00,08,00,01,00,ff" appweb7202.ethz.ch`

**Comment by PeterMosmans** [comment]
This sounds a bit like the 'infamous' *cough* Cisco loadbalancing bug, where a maximum number of ciphers in the handshake is allowed. Could you use this script at https://github.com/PeterMosmans/security-scripts/blob/master/test_ssl_handshake.sh to see whether it fails at, say 128 ciphers ? See also https://github.com/PeterMosmans/openssl/issues/28

**Comment by teward** [comment]
@PeterMosmans With nothing to do today, I ran your script against the site here in this post, using the openssl binary bundled with the testssl.sh tool:

```
% ./test_ssl_handshake.sh --openssl=/home/teward/tools/testssl.sh/bin/openssl.Linux.x86_64-krb5 appweb7202.ethz.ch    
test_ssl_handshake starting on 13-05-2016 at 19:52
BETA VERSION - bugs are present and not all features are correctly implemented
first trying to connect to appweb7202.ethz.ch:443 using 161 ciphers...
no issues detected
testing for version intolerant server (using previously loaded cipherstring)
test 1 of 6 - connect without a protocol specified 
FAILED TEST: handshake successful
testing for 128 cipherlimit
Adding 126 to 136 ciphersuites
total number of ciphers 127 - cipher added: AECDH-DES-CBC3-SHA
total number of ciphers 128 - cipher added: ADH-DES-CBC3-SHA
total number of ciphers 129 - cipher added: ECDH-RSA-DES-CBC3-SHA
total number of ciphers 130 - cipher added: ECDH-ECDSA-DES-CBC3-SHA
total number of ciphers 131 - cipher added: DES-CBC3-SHA
total number of ciphers 132 - cipher added: RSA-PSK-3DES-EDE-CBC-SHA
total number of ciphers 133 - cipher added: KRB5-DES-CBC3-SHA
total number of ciphers 134 - cipher added: KRB5-DES-CBC3-MD5
total number of ciphers 135 - cipher added: EXP1024-DHE-DSS-DES-CBC-SHA
total number of ciphers 136 - cipher added: EDH-RSA-DES-CBC-SHA
FAILED TEST: tried 136 ciphers
testing for RSA order sensitivity
test 1 of 3 - using cipherstring ALL
test 2 of 3 - using cipherstring ALL:+aRSA
FAILED TEST: handshake successful
```

------

Oddly enough, however, using a static-compiled version of your fork of OpenSSL that I built today on my Ubuntu Trusty 14.04 system, fails critically (I like having the latest stuff, heh):

```
% ./test_ssl_handshake.sh --openssl=/usr/local/bin/openssl_1.0.2 appweb7202.ethz.ch                               
test_ssl_handshake starting on 13-05-2016 at 19:54
BETA VERSION - bugs are present and not all features are correctly implemented
first trying to connect to appweb7202.ethz.ch:443 using 149 ciphers...
could not connect to appweb7202.ethz.ch:443 with all ciphers... exiting
```

**Comment by teward** [comment]
@PeterMosmans And with a copy of your OpenSSL fork (latest), with Kerberos ciphers available:

```
% ./test_ssl_handshake.sh --openssl=/usr/local/bin/openssl_1.0.2 appweb7202.ethz.ch
test_ssl_handshake starting on 13-05-2016 at 20:03
BETA VERSION - bugs are present and not all features are correctly implemented
first trying to connect to appweb7202.ethz.ch:443 using 163 ciphers...
no issues detected
testing for version intolerant server (using previously loaded cipherstring)
test 1 of 6 - connect without a protocol specified 
FAILED TEST: handshake successful
testing for 128 cipherlimit
Adding 126 to 136 ciphersuites
total number of ciphers 127 - cipher added: AECDH-DES-CBC3-SHA
total number of ciphers 128 - cipher added: ADH-DES-CBC3-SHA
total number of ciphers 129 - cipher added: ECDH-RSA-DES-CBC3-SHA
total number of ciphers 130 - cipher added: ECDH-ECDSA-DES-CBC3-SHA
total number of ciphers 131 - cipher added: DES-CBC3-SHA
total number of ciphers 132 - cipher added: RSA-PSK-3DES-EDE-CBC-SHA
total number of ciphers 133 - cipher added: KRB5-DES-CBC3-SHA
total number of ciphers 134 - cipher added: KRB5-DES-CBC3-MD5
total number of ciphers 135 - cipher added: EXP1024-DHE-DSS-DES-CBC-SHA
total number of ciphers 136 - cipher added: EDH-RSA-DES-CBC-SHA
FAILED TEST: tried 136 ciphers
testing for RSA order sensitivity
test 1 of 3 - using cipherstring ALL
test 2 of 3 - using cipherstring ALL:+aRSA
FAILED TEST: handshake successful
```

Just to be thorough ;)

**Comment by drwetter** [comment]
strange, indeed. @matteocorti: You know whether there'e something in front of the IIS7?

@PeterMosmans for TLS <1.2  your won't probably reach the limit for the CISCO. 

Also the preference tests falis. There should be more ciphers. 
```
 
 Testing all 181 locally available ciphers against the server, ordered by encryption strength 

Hexcode  Cipher Suite Name (OpenSSL)    KeyExch.   Encryption Bits        Cipher Suite Name (RFC)
--------------------------------------------------------------------------------------------------------------------------
 xc014   ECDHE-RSA-AES256-SHA           ECDH 521   AES        256         TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA                
 x35     AES256-SHA                     RSA        AES        256         TLS_RSA_WITH_AES_256_CBC_SHA                      
 xc013   ECDHE-RSA-AES128-SHA           ECDH 521   AES        128         TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA                
 x2f     AES128-SHA                     RSA        AES        128         TLS_RSA_WITH_AES_128_CBC_SHA                      
 x0a     DES-CBC3-SHA                   RSA        3DES       168         TLS_RSA_WITH_3DES_EDE_CBC_SHA        
```
I tried with earlier release, it;s the same. The socket reply is just empty (TLS 1.0). The thing is that in wireshark it is not. There all looks ok (tried ``testssl.sh --debug=6 --devel "01" "c0,14"  appweb7202.ethz.ch``)

**Comment by matteocorti** [comment]
Hi, there is nothing in front of IIS ...

**Comment by drwetter** [comment]
Hi @matteocorti,

I haven't found  any IIS7 in the interweb (shodan search) which behaves the same as yours (no TLS 1.0 and only one cipher in preferences).

So thx for reporting. It needs to be addressed. Maybe it helps to understand first why your server is different. As I can't reproduce it on other IIS7 I would label it is a minor bug.

Cheers, Dirk

**Comment by jandr** [comment]
Hi, 

just to add to this issue, I have found the same in a CDN:  support13.cdnetworks.net

 Testing protocols via sockets except SPDY+HTTP2 

 SSLv2      not offered (OK)
 SSLv3      not offered (OK)
 TLS 1      not offered
 TLS 1.1    not offered
 TLS 1.2    not offered
 SPDY/NPN   not offered
 HTTP2/ALPN not offered

**Comment by drwetter** [comment]
@jandr thx. 

Indeed, that is another strange one.

With ``--ssl-native`` I get TLS 1.2 returned and other results.


PS: The server above (appweb7202.ethz.ch) doesn't seem to be online anymore.

**Comment by dcooper16** [comment]
I got the same odd results - successful connections with OpenSSL but no response with `tls_sockets()`. I even tried modifying `tls_sockets()` so that is was sending the exact same ClientHello as OpenSSL was (with the exception of using a different value for "random") and it still didn't work.

I tried using Wireshark to compare what was being sent with OpenSSL versus `tls_sockets()` and there was only one thing that I noticed that was different (see below). In the case of OpenSSL Wireshark just shows a packet of length 203 bytes being sent, whereas with `tls_sockets()` Wireshark shows the ClientHello being segmented across two packets. I don't know of any way to change `tls_sockets()` so that the ClientHello isn't segmented, so I can't test whether that the is reason for the failure, but so far I haven't been able to find any other possible explanation for why OpenSSL and `tls_sockets()` are producing different results.

![openssl](https://user-images.githubusercontent.com/16493199/28437057-3247549c-6d67-11e7-9f22-6672d295f9e7.png)

![testssl](https://user-images.githubusercontent.com/16493199/28437064-3d676600-6d67-11e7-98b7-b2eb6ac49aa3.png)

**Comment by drwetter** [comment]
what appears strange to me that there's _zero_ serverhello if e.g. running ``./testssl.sh -p --debug=6 --ip=one  support13.cdnetworks.net``.

**Comment by drwetter** [comment]
Housekeeping: I am closing this as appweb7202.ethz.ch didn't come back. support13.cdnetworks.net works now -- don't know whether a change at the server side or @dcooper16's socket code is responsible (in a positive sense) for it. 

Happy to reopen if there are new findings.
