### ISSUE TITLE
New TLS 1.2 overflow (regression)

### ISSUE THREAD

**Issue by drwetter** [drwetter/testssl.sh#378]
While #189 was fixed I figured that ``-E`` in those case with TLS 1.2 doesn't show a single cipher :-( 

@dcooper16 : would you be able to look into it if @feld allows me to pass the hostname to you? I suppose ``OPENSSL s_client -cipher "${ciphers_to_test:1}" `` in ``run_cipher_per_proto()`` is the culprit.

Current status in this particular case is
```
 Testing all locally available ciphers per protocol against the server, ordered by encryption strength 

Hexcode  Cipher Suite Name (OpenSSL)    KeyExch.   Encryption Bits        Cipher Suite Name (RFC)
--------------------------------------------------------------------------------------------------------------------------
SSLv2 
SSLv3 
TLS 1 
 x35     AES256-SHA                     RSA        AES        256         TLS_RSA_WITH_AES_256_CBC_SHA                      
 x2f     AES128-SHA                     RSA        AES        128         TLS_RSA_WITH_AES_128_CBC_SHA                      
 x0a     DES-CBC3-SHA                   RSA        3DES       168         TLS_RSA_WITH_3DES_EDE_CBC_SHA                     
TLS 1.1 
 x35     AES256-SHA                     RSA        AES        256         TLS_RSA_WITH_AES_256_CBC_SHA                      
 x2f     AES128-SHA                     RSA        AES        128         TLS_RSA_WITH_AES_128_CBC_SHA                      
 x0a     DES-CBC3-SHA                   RSA        3DES       168         TLS_RSA_WITH_3DES_EDE_CBC_SHA                     
TLS 1.2 

```

Whereas before it was 
```
Testing all locally available ciphers per protocol against the server, ordered by encryption strength 

Hexcode  Cipher Suite Name (OpenSSL)    KeyExch.   Encryption Bits
-------------------------------------------------------------------------
SSLv2 
SSLv3 
TLS 1 
 x35     AES256-SHA                     RSA        AES        256                                                                                     
 x2f     AES128-SHA                     RSA        AES        128                                                                                     
 x0a     DES-CBC3-SHA                   RSA        3DES       168                                                                                     
TLS 1.1 
 x35     AES256-SHA                     RSA        AES        256                                                                                     
 x2f     AES128-SHA                     RSA        AES        128                                                                                     
 x0a     DES-CBC3-SHA                   RSA        3DES       168                                                                                     
TLS 1.2 
 x35     AES256-SHA                     RSA        AES        256                                                                                     
 x3c     AES128-SHA256                  RSA        AES        128                                                                                     
 x2f     AES128-SHA                     RSA        AES        128                                                                                     
 x0a     DES-CBC3-SHA                   RSA        3DES       168                    

```

$SERVER_SIZE_LIMIT_BUG is the global var which is supposed to track size limitations of the ClientHello a server is accepting.

**Comment by dcooper16** [comment]
Hi @drwetter,

I posted some code to https://github.com/dcooper16/testssl.sh/blob/run_allciphers128limit/testssl.sh that changes both run_allciphers() and run_cipher_per_proto() so that no call to $OPENSSL s_sclient includes 128 or more ciphers suites in the ClientHello (the change has no impact on $OPENSSL s_sclient unless $OPENSSL offers more than 256 cipher suites). Either you or @feld can try it out to see if it is works on the affected server, if @feld would prefer not to pass the hostname to me.

**Comment by drwetter** [comment]
Hi there @dcooper16 ,

perfect. ``run_cipher_per_proto()`` works as one would expect with the host from @feld .
Fixing ``run_allciphers()`` doesn't seem necessary, it worked well before.

Q: Just wondering whether the fix in  L1220 costs more connects? If so I would rather have a check in there like https://github.com/drwetter/testssl.sh/blob/master/testssl.sh#L2825-2829 . There it penalizes the majority of users only with _one_ additional connect.

Cheers! Dirk

**Comment by dcooper16** [comment]
At the moment the change to `run_allciphers()` doesn't actually do anything, since it would only change things if more than 256 ciphers suites were being tested, and no version of OpenSSL supports that many cipher suites. However, I included it for the (possible) future when `run_allciphers()` uses `tls_sockets()`, which would allow for over 300 cipher suites to be tested.

In the case of` run_cipher_per_proto()`, the impact is as follows:
- SSLv2: no change
- SSLv3, TLSv1, TLSv1.1, TLSv1.2:
    - one less test if the server supports the protocol
    - two more tests if the server does not support the protocol (given that OpenSSL supports fewer than 192 non-SSLv2 ciphers)

The solution in https://github.com/drwetter/testssl.sh/blob/master/testssl.sh#L2825-2829 doesn't seem to do any better. If `$OPENSSL s_client` fails in L2825, then it seems that _two_ more calls are done to `$OPENSSL s_client`, one with `ALL:$tested_cipher:$batchremoved` and one with `$batchremoved`.

David

**Comment by drwetter** [comment]
Hi David,

then please give me a PR to get this through.

BTW: && nn the long run: There's a variable and a function which is supposed to keep the state whether a protocol is supported or not (``has_server_protocol()`` , ``$PROTOS_OFFERED``)

Cheers! Dirk

**Comment by drwetter** [comment]
closing, see #380
