### ISSUE TITLE
Cygwin requires bind-utils

### ISSUE THREAD

**Issue by SeanPGit** [drwetter/testssl.sh#550]
Running under Cygwin x64 under Windows 10 x64, testssl.sh (obtained using curl) always returned the error 👍 Fatal error: No IPv4 address for "<hostname>" available, for any <hostname> (FQDN) I tried.
If I substituted the IP address for <hostname> it was OK.

Checking for the reason for the error in the script, I noticed that it tried a number of utilities, including nslookup, before returning the error. Indeed nslookup.

I noted that it was using the Windows version of nslookup, which on my machine (for reasons I cannot determine) returned the following error:
H:\>nslookup <hostname>
Server:  UnKnown
Address:  fe80::c63d:c7ff:fea1:2c12

*** UnKnown can't find <hostname>: Query refused

OK - in fact that may be the root cause of the issue, and for most people with a working nslookup in windows, it may work?

However, the resulution for me was to install the bind-utils package with Cygwin. 
Perhaps the tools could make extra sanity checks for this error - or suggest the package for Cygwin?

(I'll try it on another Windows machine - just to see if it makes a difference with / without bind-utils package).

--
Sean

**Comment by drwetter** [comment]
Hi Sean,

> Running under Cygwin x64 under Windows 10 x64, testssl.sh (obtained using curl) always 

Please note you miss e.g. the certificate stores and in 2.9dev partly the cipher mapping if you dl only testssl.sh. Plan for the future is also to separate code from data.

> returned the error 👍 Fatal error: No IPv4 address for "" available, for any (FQDN) I tried.
If I substituted the IP address for it was OK.

You could end up at the wrong virtual host. YOu might want to give ``./testssl.sh --ip=<IPADRESS> <HOST>`` a try.

> I noted that it was using the Windows version of nslookup, which on my machine (for reasons I cannot determine) returned the following error:
H:>nslookup
Server: UnKnown
Address: fe80::c63d:c7ff:fea1:2c12
>
> *** UnKnown can't find : Query refused

To be honest I don't remember whether the windows "nslookup" works. I guess it does but can't recall for sure.

But the problem is that your DNS doesn't work -- at least not using this nslookup. The output tells you there's no server on an IPv6 link-local address: https://en.wikipedia.org/wiki/Link-local_address#IPv6

For some reason (neighbor discovery, misconfigured SLAAC,...) nslookup has determined fe80::c63d:c7ff:fea1:2c12 is the IP address of your DNS server. ``Query refused`` tells you that is doesn't work -- for whatever reasons.

> Perhaps the tools could make extra sanity checks for this error - or suggest the package for Cygwin?

Well, testssl tries different tools for DNS lookups. If all fails it bails out with an error ``No IPv4 address for \"$NODE\" available``, I am hesitant to put more intelligence here into it as I think using a tool should be like a swiss army knife and not behave like hal9000 or part of skynet  ;-)
