### ISSUE TITLE
Show IP

### ISSUE THREAD

**Issue by AgoraSecurity** [drwetter/testssl.sh#561]
Hello,

It would be nice to add a feature (for instance a parameter) to show the IP on all the groups of testings.

That would be helpful for reporting purposes.

For example, I have to check 5 websites. Two have issues and are different. #1 don't offer good protocols, #2 don't offer good protocols + is vulnerable to BEAST.

The idea of having the IP on each block of tests would be quite useful for screenshots, etc.

Cheers!

**Comment by drwetter** [comment]
Hi there!

Am 12/13/2016 um 07:22 PM schrieb Agora Security:
> Hello,
> 
> It would be nice to add a feature (for instance a parameter) to show the IP on all the groups
> of testings.
> 
> That would be helpful for reporting purposes.
> 
> For example, I have to check 5 websites. Two have issues and are different. #1
> don't offer good protocols, #2 don't offer good protocols + is vulnerable to
> BEAST.
> 
> The idea of having the IP on each block of tests would be quite useful for screenshots, etc.

Honestly I am not a friend of this as it blows up the screen output. It's already quite a
piece of work to deliver all necessary info on the screen and not overloading it.


2-3 recommendations:

* use (flat) JSON or CSV output
* use flat or pretty JSON or CSV output with the severity flag
* retest with the section flag (1: -p, 2: -p -A) so that the IP address is closer on the screen
* log to file (--log) and remove the sections you don't need (admittedly s.th. which doesn't scale)

Other than that: also for screen output there's a feature request to make use of the severity flag.
That requires quite some work though but I am sure this will come.

Cheers, Dirk
