### ISSUE TITLE
Is CCS (CVE-2014-0224)  fix on openssl 1.0.1q?

### ISSUE THREAD

**Issue by KpaHuang** [drwetter/testssl.sh#584]
I checked the openssl 1.0.1q should already include CCS bug fix.
But I got fail when I test CCS injection vulnerability.
The weird thing is CCS pass in my Cygwin. The dump is "not vulnerable (OK), timed out".
Is something wrong with 1.0.1q version? or should I apply other setting to pass this item?

When I run testssl in Ubuntu 16.04.1. CCS is fail.
When I run testssl in Cygwin. CCS is OK (time out)

**Comment by drwetter** [comment]
Yes, CCS injection is from 2014 (CVE-2014-0224) and your openssl version is from January 2016.

There seem to be two issues here:
1) a potential false positive. You have an IP address for me (pm is fine)?
2) The timeout under Cygwin. 

The latter could be due to the fact that sockets under Cygwin/MSYS4 are slower. I never needed to but what if you run the thing like ``CCS_MAX_WAITSOCK=20 ./testssl.sh -I <TARGETSPEC>``?

**Comment by drwetter** [comment]
timed out, autoclosing. Let me know if you have new information then I am happy to reopen
