### ISSUE TITLE
QQ: no SSL message

### ISSUE THREAD

**Issue by mgaulton** [drwetter/testssl.sh#596]
Hey There, 

I had one of my server admins come over because when he self-tested with the script, he got the below message. I believe this may be because no SSL is offered, though TLS is and its not sure what to think.

Can anyone confirm this theory?

 Testing server preferences

 Has server cipher order?     yes (OK)
 Negotiated protocol          TLSv1.2
 Negotiated cipher            ECDHE-RSA-AES256-GCM-SHA384, 256 bit ECDH
 Cipher order
    TLSv1:     ECDHE-RSA-AES256-SHA AES256-SHA CAMELLIA256-SHA ECDHE-RSA-AES128-SHA AES128-SHA CAMELLIA128-SHA
    TLSv1.1:   ECDHE-RSA-AES256-SHA AES256-SHA CAMELLIA256-SHA ECDHE-RSA-AES128-SHA AES128-SHA CAMELLIA128-SHA
    TLSv1.2:   ECDHE-RSA-AES256-GCM-SHA384 ECDHE-RSA-AES256-SHA384 ECDHE-RSA-AES256-SHA AES256-GCM-SHA384 AES256-SHA256 AES256-SHA CAMELLIA256-SHA ECDHE-RSA-AES128-GCM-SHA256 ECDHE-RSA-AES128-SHA256 ECDHE-RSA-AES128-SHA AES128-GCM-SHA256 AES128-SHA256 AES128-SHA CAMELLIA128-SHA
    http/1.1:  ECDHE-RSA-AES256-GCM-SHA384 ECDHE-RSA-AES256-SHA384 ECDHE-RSA-AES256-SHA AES256-GCM-SHA384 AES256-SHA256 AES256-SHA CAMELLIA256-SHA ECDHE-RSA-AES128-GCM-SHA256 ECDHE-RSA-AES128-SHA256 ECDHE-RSA-AES128-SHA AES128-GCM-SHA256 AES128-SHA256 AES128-SHA CAMELLIA128-SHA

Strange, no SSL/TLS protocol seems to be supported (error around line 3988)

**Comment by dcooper16** [comment]
No, that's not the problem. It's good that the server doesn't offer SSLv2 or SSLv3.

The fact that you're getting this error message, and that it is indicating the error is occurring at around line 3988, however, suggests that you are using an old version of testssl.sh, but I can't figure out which version you are using. Try using the latest version from GitHub or the stable version 2.8 from https://testssl.sh.

**Comment by mgaulton** [comment]
testssl.sh       2.8rc2 from https://testssl.sh/dev/

It was recently updated by my boss.

**Comment by dcooper16** [comment]
Okay, I think I found it. Given that it is reporting "(error around line 3988)" and that it was a pre-release draft of version 2.8, it appears that your boss is using a version of the development branch from mid-September.
As a starting point, try the latest version from https://testssl.sh/dev (2.9dev) and/or the stable version 2.8 from https://testssl.sh. Note that version 2.8 was just updated on January 20, and the development version (2.9dev) is being modified frequently (most recently this morning).

If the problem is still occurring, then there might be a problem with testssl.sh, but more information would be needed in order to look into it, as noted in https://github.com/drwetter/testssl.sh/wiki/Bug-reporting.

**Comment by mgaulton** [comment]
Awesome, thanks. I'll get back to you.

**Comment by kraigu** [comment]
@mgaulton 's boss here :) I did a pull off master, I thought:
origin	https://github.com/drwetter/testssl.sh (fetch)
origin	https://github.com/drwetter/testssl.sh (push)
but I'll update with 2.8 and we'll see if we can reproduce.

**Comment by kraigu** [comment]
Ah, I'd pulled master but mis-deployed. Will need to get @mgaulton to help with double-checking the original server, but this was likely a process failure, not a testssl.sh failure.

**Comment by mgaulton** [comment]
After the update, the host no longer generates that message.
