### ISSUE TITLE
RFC names in wide output / -e , -E

### ISSUE THREAD

**Issue by drwetter** [drwetter/testssl.sh#631]
``neat_header()`` and ``neat_list()`` need to be changed too after #630 .

**Comment by drwetter** [comment]
I think the switches for ``--mapping`` should be clarified like:

rfc-only | rfc ==> displays only RFC  names in output
openssl-only | openssl ==>  displays only openssl names in output
both  ==> default

**Comment by bknowles** [comment]
👍

**Comment by dcooper16** [comment]
I tried to address this issue with PR #646.

I don't believe having three options of "rfc-only", "openssl-only", and "both" works. These three options might work for information that is printed in wide mode, but not in other places (e.g., client simulation, pfs, negotiated cipher, cipher order). In these places, testssl.sh needs to display either the OpenSSL name or the RFC name.

That's why #630 only added an "rfc" choice. I wanted a way to print the RFC name rather than the OpenSSL name in places where testssl.sh could only print one or the other, but I don't see a problem with just printing both in wide mode, when both can be printed.

By providing 4 choices for the `--mapping` option (including the default one), the user can not only request that only the OpenSSL name or only the RFC name be printed, but can request that both be printed in wide mode while choosing which name type should be used in places where only one or the other can be printed.

**Comment by drwetter** [comment]
see #646
