### ISSUE TITLE
Bad substitution, line 518

### ISSUE THREAD

**Issue by ilya-il** [drwetter/testssl.sh#697]
Hello! 

I run version 2.8
`./testssl.sh -t smtp my.mail.server:25 `
got error
`Service set:            STARTTLS via ./testssl.sh: line 518: ${1^^}: bad substitution`

My distro is SLES 11SP4 x64

**Comment by drwetter** [comment]
Am 05.04.2017 um 16:54 schrieb Ilya IL:
> Hello!
> 
> I run version 2.8
> |./testssl.sh -t smtp my.mail.server:25|
> got error
> |Service set: STARTTLS via ./testssl.sh: line 518: ${1^^}: bad substitution|
> 
> My distro is SLES 11SP4 x64

Hmm, for sure that doesn't work with bashv3 .

But SLES11 has a more recent one. What does ``bash --version`` say?

Cheers, Dirk

**Comment by ilya-il** [comment]
Thanx for your work! ``bash --version`` says

```
bash --version
GNU bash, version 3.2.57(2)-release (x86_64-suse-linux-gnu)
```

I've downloaded testssl.sh 2.9dev. It has same error on line 1145

`./testssl.sh: line 1145: ${1^^}: bad substitution`

**Comment by drwetter** [comment]
Should work now, thx for reporting!

The last error you spotted was because bash3 hiccuped at this definition ( which later was overwritten).
bash3 seems also to be picky regarding redirecting that error, so again I needed to rearrange the logic.

The good thing now is that all folks using bash4 are using the faster version of ``toupper()``/``tolower()``.
