### ISSUE TITLE
Browsers deprecating Subject/CommonName in favor of Subject Alternative Names

### ISSUE THREAD

**Issue by tkaehn** [drwetter/testssl.sh#733]
Hi,

Browsers are deprecating Subject/CommonName matching in favor of Subject Alternative Names. My suggestion is that testssl.sh should at least warn if no SAN is specified. Further tests might be possible as well. What do you think about this?

https://textslashplain.com/2017/03/10/chrome-deprecates-subject-cn-matching/
https://groups.google.com/a/chromium.org/forum/#!topic/security-dev/IGT2fLJrAeo

Best regards,
Thomas

**Comment by drwetter** [comment]
Probably reasonable.... 
I also read the SSLlabs stuff at github:)  Thx for the feature request. 

The long time it takes sounds a bit like IPv6... 


Cheers, Dirk

⁣-- 
Sent via mobile. Excuse my brevity, my typos and the autocorrection​

**Comment by drwetter** [comment]
see #735

**Comment by dcooper16** [comment]
I believe that #735 doesn't fully address this issue. This issue also needs to be addressed in the "Trust (hostname)" line. At the moment, that line says it is OK if the presented if the SAN is missing, but the presented name matches the CN.

The logic for the "Trust (hostname)" line is somewhat complicated, dealing with all the possibilities for the CN and SAN in both the certificate returned when SNI is used and the certificate returned when SNI is not used.

**Comment by drwetter** [comment]
Hi @dcooper16 ,

apologize, after reading it on my mobile your comment slipped past me.

**Comment by drwetter** [comment]
> This issue also needs to be addressed in the "Trust (hostname)" line. At the moment, that line says it is OK if the presented if the SAN is missing, but the presented name matches the CN.

Agreed, that would be the better approach.

> The logic for the "Trust (hostname)" line is somewhat complicated, dealing with all the possibilities for the CN and SAN in both the certificate returned when SNI is used and the certificate returned when SNI is not used.

Okay, that's true. SNI complicates matters. As it anyway the robust logic you did and maybe it's the easiest if you could do a PR?

Cheers, Dirk

**Comment by dcooper16** [comment]
> apologize, after reading it on my mobile your comment slipped past me.

No problem. I had already forgotten that I had commented on this issue :-)

I'll try to develop a PR for this. I've been working on an unrelated PR, and I'll get to work on this after I submit that one.

**Comment by drwetter** [comment]
Hi @dcooper16 ,

maybe you could have a look at it, see commit comment. Chrome 58 shows a warning so I felt like addressing it soon.

For this WIP I created a separate branch.

Cheers, Dirk

**Comment by dcooper16** [comment]
Okay. I had done some work on this, but wasn't entirely satisfied with what I had developed so far, which is why I hadn't created a PR yet.

I believe that there is an inconsistency in the level of warning in the SAN_preferred branch. According to my parsing of the old and new logic, here is the level of warning given when the presented name doesn't match the SAN in the certificate:

row | $trust_sni | Has SAN | Service | Old Severity Level | New Severity Level
-----|-------------|-------------|-----------|-------------------------|-------------------------
1 | 0 (no match in SAN or CN) |  |  | medium | medium
2 | 4 or 8  (matches CN) | no | HTTP | no warning | high
3 | 4 or 8  (matches CN) | yes | HTTP | medium | high
4 | 4 or 8  (matches CN) | no | not HTTP | no warning | medium
5 | 4 or 8  (matches CN) | yes | not HTTP | medium | medium

So now, in the case of HTTP, a matching CN (without a matching SAN) is considered worse than no match at all, whereas the browsers are treating the two cases as equivalent. It seems that rows 1, 2, 3, and 5 should be marked as one severity level (since current clients will not consider the certificate to be a match) and row 4 should be marked at a lower level (since it is deprecated, but current clients may still consider it to be a match). It's just a question of whether the two levels should be high/medium, high/low, or medium/low.

**Comment by dcooper16** [comment]
I just submitted PR #761 to try to address the remaining issues. Most of the changes are in the section dealing with the certificate obtained without SNI, but I made a few changes for the SNI case. I changed the severity level to HIGH if the certificate does not match at all, in order to match the case in which the service is HTTP and there is only a match in the CN. I also reorganized the code a bit to remove some redundancy.

For the certificate obtained without SNI the logic is more complicated, so I'll try to explain it here (and I included a comment in the code referencing this issue). First, if the results are the same with and without SNI, then the output just says " (same w/o SNI)", whether that means the results were just as good without SNI or just as bad. If the results with and without SNI differed, then the output is as follows:

result w/o SNI | result w/ SNI | output | explanation
------------------|------------------|---------|----------------
0 | 1, 2, 5, 6, 9, or 10 | ( SNI mandatory) | Matching works with SNI but not without
0 | 4 or 8 | (w/o SNI: certificate does not match supplied URI) | " (SNI mandatory)" doesn't seem appropriate, since matching may not work even without SNI, but there is a "better" match with SNI.
4 or 8 |   | (w/o SNI: ... ) | "..." is the string that would have been output if the certificate had been obtained with SNI. In this case, the certificate is different than the one sent with SNI, and it identifies the server, but the matching isn't good, so it seems that he problem with the certificate should be described.
1, 2, 5, 6, 9, or 10 | 0 | (however, works w/o SNI) | Extremely unlikely scenario in which certificate matches provided server name if SNI not provided, but does not match at all if SNI provided.
1, 2, 5, 6, 9, or 10 | 1, 2, 5, 6, 9, or 10  | (works w/o SNI) | The provided certificate matches both when SNI is provided and when it is not.
1, 2, 5, 6, 9, or 10 | 4 or 8 |  (w/o SNI: ... ) | "..." is the string that would have been output if the certificate had been obtained with SNI. In this case, the certificate is different than the one sent with SNI, it identifies the server, and the matching is better than with the certificate obtained with SNI, so it seems this should be mentioned.

The severity level for the certificate obtained without SNI is as follows:
- If the match without SNI is 4 or 8, then it is assumed that the server operator intended for the certificate to match the presented name and so the severity level is the same as if it were returned with SNI: HIGH for service=HTTP and MEDIUM for other services
- If the certificate is a good match (1, 2, 5, 6, 9, or 10) or if it doesn't match at all, then `outln` is used, since there seems to be no need to flag anything in this case.

**Comment by drwetter** [comment]
Thanks a lot, David! I gave it some tests in real life, looks great.

The only thing is just a matter of policy which I am not sure about yet: The level of punishment. We currently have HIGH for CN-only match (browser).  Just depends on Firefox' & Chrome's future behaviour.
