### ISSUE TITLE
Order of arguments for batch processing 

### ISSUE THREAD

**Issue by drwetter** [drwetter/testssl.sh#749]
While running

``./testssl.sh --file=f5.txt -S -T --logfile=f5serial.log  --csvfile=f5serial.csv`` I discovered that this doesn't do what I expected, i.e. it doesn't honor the additional flags supplied ``-S -T`` but instead does a full scan.

This ``./testssl.sh -S -T --append --file=f5.txt  --logfile=f5serial.log  --csvfile=f5serial.csv`` works as expected. So the order seems of ``--file`` ``-S -T`` relevant.

Same applies for mass parallel scanning.

**Comment by dcooper16** [comment]
Hi Dirk,

Sorry about that. For some reason I thought that the `--file <fname>` option had to come last. I think it will be a small change to make it so that it can appear earlier in the command line, but I'll have to work on that next week.

That may explain what you are seeing in #751. Issue #750 seem very odd since the text that is appearing the log file is being sent to `stderr` and logging of the parent only captures `stdout`, but it may also be related to my incorrect assumption that the `--file <fname>` option had to come at the end of the command line.

**Comment by drwetter** [comment]
Hi David,

okay :-) if it the parallel scanning works finally it's a another big step forward.

Cheers, Dirk



Cheers, Dirk

**Comment by drwetter** [comment]
closed via 041abd57ce8b8c06c9a62f836e853272e69fb294
