### ISSUE TITLE
DES-CBC-SHA gives incorrect results?

### ISSUE THREAD

**Issue by t3sting4me** [drwetter/testssl.sh#770]
I've noticed the testssl.sh script output shows the server the DES-CBC3-SHA Cipher output as 168bits. However when running scans with nmap, ssllabs and sslscan the results would always return the cipher as weak and accepts 112 bits.

**Comment by drwetter** [comment]
good point. It depends on the keying option. I was always under the impression it's three keys (3x56). There's the Meet-in-the-Middle attack which reduces the keyspace effectively by one key thus resulting in 112 bits.

The problems to rephrase that are two: 
* I don't want just to mimic others unless it's a official saying (RFC, NIST etc), I'd rather to like understand this better
* If we start taking into account reduction of key spaces due to known attack vectors we maybe need to rephrase the bitsize for other ciphers or any cryptographic algorithms.

@dcooper16 : NIST still refers in their publications to TDEA (Triple DES). Couldn't figure what their stance is regarding the bitlength. Any idea?

**Comment by dcooper16** [comment]
Hi @drwetter ,

I think this is just a matter of whether one wants to show _bit length_ or _security strength_. It seems that SSL Labs shows bit length for asymmetric keys and bit strength for symmetric keys, whereas testssl.sh always shows bit length.

RFC 5246 says:

> DES can also be operated in a mode [3DES] where three independent keys and three encryptions are used for each block of data; this uses 168 bits of key (24 bytes in the TLS key generation method) and provides the equivalent of 112 bits of security.

This is consistent with what testssl.sh shows. It lists 3DES as having 168 bits, but when listing cipher suites in order of encryption strength it lists the 3DES ciphers after the 128-bit ciphers (that actually provide 128 bits of security).

I don't believe that NIST offers any stance on the bit length of a three-key TDEA key. It does, however, agree with RFC 5246 that three-key TDEA only provides 112 bits of security: Table 2 of [SP 800-57 Part 1](http://dx.doi.org/10.6028/NIST.SP.800-57pt1r4).

**Comment by drwetter** [comment]
Good explanation, @dcooper16 . I added that to the documentation / future man page (currently in the wiki). 

``ciphers(1)`` from openssl could be better though as on one hand that man page refers to encryption column without mentioning what is shown there (size or strength). Then it says _Additionally the cipher string @STRENGTH can be used at any point to sort the current cipher list in order of encryption algorithm key length_ -- not _encryption strength_. According to that ``openssl ciphers -V 3DES:AES:@STRENGTH`` is not what is does.

The latter is still in 1.1.1...
