### ISSUE TITLE
Change "key:value" notation in field "finding"

### ISSUE THREAD

**Issue by fogs** [drwetter/testssl.sh#830]
Currently, the "finding" field in JSON output may contain a "key : value" pairs, such as:

```
       "finding"      : "OCSP stapling : not offered"
```

While that "key : value" format is helpful when directly displayed to the user, it requires parsing when only the value part is needed. Example scenarios are displaying the scan results in a table where the key part is the columns header but should not repeat in every cell. Also any other type of further processing the data, like monitoring on certificate expiration dates or counting the list of SAN of a certificate.

My recommendation would be to add a command line switch to suppress the key part in the finding (in the above example "OCSP stapling") as well as " : " and only include the value part (again in above example "not offered").

**Comment by drwetter** [comment]
Just doing some brainstorming over this while working on a similar matter...

As privately communicated: It would makes sense.  So instead of:

```
       {
              "id"           : "ocsp_stapling",
              "ip"           : "AAAA/190.10.XX.YY",
              "port"         : "443",
              "severity"     : "INFO",
              "finding"      : "OCSP stapling : not offered"
          }
```

an output like

```
       {
              "id"           : "ocsp_stapling",
              "ip"           : "AAAA/190.10.XX.YY",
              "port"         : "443",
              "severity"     : "INFO",
              "finding"      : not offered"
          }
```
(change in last line)

It would be a bit at the cost of readability for humans and as you said a breaking change. But sometimes there need to be changes and  I hope if people use the dev tree they don't to a git pull and run it without review 1:1 in production.

So  I labeled it accordingly to be included into next release but I might later push the change beyond this

**Comment by drwetter** [comment]
closing this, see #970 (also for continuing any communication)
