### ISSUE TITLE
-b/-v: running from git & finding openssl binary

### ISSUE THREAD

**Issue by tecknicaltom** [drwetter/testssl.sh#870]
bin/Readme.md states:

  The binaries ... will be picked up from testssl.sh if you run testssl.sh directly off the git directory.

This doesn't appear to be happening right now. Running from the git repo without specifying the openssl binary explicitly results in using the system binary. The best I can tell is that `TESTSSL_INSTALL_DIR` should be initialized to $RUN_DIR, but right now it defaults to an empty string.

**Comment by amckenna** [comment]
Confirmed, having the same issue.

**Comment by drwetter** [comment]
I can't reproduce it -- running a real check. I can reproduce this though if I just run `` ./testssl.sh -b`` or ``./testssl.sh -v``. (this is a minor bug and needs to be resolved)

Is it that what you mean?

Otherwise I would need more info about your environment, e.g. by running ``testssl.sh --debug=1 -p dev.testssl.sh``, give me the file ``/tmp/testssl.????/environment.txt`` and tell exactly how you started it, e.g. ``./testssl.sh`` or ``testssl.sh``, is there any link involved, etc...

Thx. Dirk

**Comment by tecknicaltom** [comment]
Ok, thanks, I was relying on the banner output to see the openssl binary location. I've confirmed that running an actual scan finds the included binary, where the banner does not. This does appear to just be an issue with the -v output. Feel free to rename and prioritize appropriately, and thanks for the guidance
