### ISSUE TITLE
complete run_server_preference()

### ISSUE THREAD

**Issue by drwetter** [drwetter/testssl.sh#893]
Hi David,

I am sure you're working on this but as a reminder (see #868)

>  It also will only show TLSv1.3 as the "Negotiated protocol" if $OPENSSL supports TLSv1.3. 

Cheers, Dirk

**Comment by dcooper16** [comment]
Hi Dirk,

I can do something here. I already have code in my [extended_tls_sockets](https://github.com/dcooper16/testssl.sh/tree/extended_tls_sockets) branch that uses `tls_sockets()` to determine the "Negotiated protocol" if `$OPENSSL` doesn't support TLSv1.3 and it hasn't previously been determined that the server does not support TLSv1.3. That code needs some work, though, since it currently sends a ClientHello with more than 128 ciphers.

The reason that I didn't address this in the first PR is that I wanted to make only minimal changes to `run_server_preference()` given issue #766 and that you have a [new_serverpref](https://github.com/drwetter/testssl.sh/tree/new_serverpref) branch.

Dave

**Comment by drwetter** [comment]
that should be done with  5c54f97

``new_serverpref`` will be done in 3.1dev. Now it's time to get the next release ready.
