### ISSUE TITLE
Need another command-line switch to prevent unnecessary DNS resolution

### ISSUE THREAD

**Issue by ivanr** [drwetter/testssl.sh#935]
I wanted to prevent reverse DNS lookups, so I tried --nodns, but that also breaks testing by hostname. Are reverse DNS lookups actually needed? If not, they should be disabled by default and enabled with a switch.

**Comment by drwetter** [comment]
Sorry, need to take that back.

IIRC it was formerly used to query at least the A/AAAA record(s). By design it doesn't do that anymore as should give users the choice not to do DNS queries at all. It works of you have an entry in /etc/hosts or do ``./testssl.sh --nodns -BB--ip=178.62.77.45 https://depot.feistyduck.com``.

That might sound a bit extreme but if you have a use cases where this is too much, I am happy to learn.

**Comment by jckruger** [comment]
Can this also be an option when you us the --file option. DNS works when I do testssl.sh www.google.com.au but if I add this to a file to use then I get the error that it cannot get the IP address "available: No IPv4/IPv6 address(es) for www.google.com.au

I'm using 2.9.5.
The addresses I am trying to connect to are on the same box with virtual hosts using the one address. Maybe that is the problem.

Cheers
Justin

**Comment by drwetter** [comment]
see commit. Let me know if you spot any problems (not my typical use cases)
