### ISSUE TITLE
Installation with Composer based on Packagist.org

### ISSUE THREAD

**Issue by ced63** [drwetter/testssl.sh#957]
Would it be possible to deploy the sources with the dependency manager named **composer** whose main repository is on [packagist](https://packagist.org) ?

This will allow us to update the sources with a simple command: `composer update`
thank you in advance

**Comment by drwetter** [comment]
It's a shell script and needs to have a wrapper. This would be a community thing outside of this project.

A piece of advice though: As a security conscious person I sanitized input (from a server to be tested) but I also have to admit that there's likely room for improvements. Thus I can't guarantee it is safe -- I would appreciate any filings of security related bugs!

Game changes to the worse if you're **not** running it from a command line and have other people using it. So if you're running off an web application I'd rather recommend to do input validation with your language of choice so that your server doesn't get pwned though scanning another server which was set up specially for this.
