### ISSUE TITLE
Check for "digitalSignature" in "keyUsage" certificate extension

### ISSUE THREAD

**Issue by firewave** [drwetter/testssl.sh#964]
rabbitmq/rabbitmq-server#867

It appears that at least Erlang/OTP has a the shortcoming, that a certificate which is missing the _digitalSignature_ extension for _keyUsage _ will cause the ciphers to be filtered leaving only the least secure ones.

As mentioned in the linked issue this is not a problem with httpd, but I am not sure how many other implementations might be affected by this or similar issues. So I am wondering if it might sense to add such a check.

**Comment by dcooper16** [comment]
Hi @firewave ,

I didn't read https://github.com/rabbitmq/rabbitmq-server/issues/867 in detail, but I believe this is a feature of Erlang/OTP, not a shortcoming. The keyUsage extension specifies the purposes for which the public key may be used. If the keyUsage extension is present and the _digitalSignature_ bit is not set, then the public key _should not_ be used to verify digital signatures. Since cipher suites such as ECDHE_* or DHE_* require the client to use the public key in the certificate to verify signatures created by the server, these cipher suites _should not_ be used if the certificate indicates that the public key _should not_ be used for verifying digital signatures.

Similarly, if the certificate included a keyUsage extension that did not set the _keyEncipherment_ bit, then cipher suites such as TLS_RSA_WITH_AES_256_GCM_SHA384 should not be used, since they would require the client to encipher a key to send to the server using a public key that the certificate indicated _should not_ be used for that purpose.

So, I don't consider it a shortcoming of Erlang/OTP that it will only use the server's key in a manner that is consistent with allowable uses as indicated by the keyUsage extension in the certificate.

That said, I have a fork of testssl.sh that displays the contents of the keyUsage and extended key usage extensions, and I could submit those changes as a PR. However, the only "check" that could be performed is to verify that server doesn't support any cipher suites that are inconsistent with the contents of the keyUsage extension, which seems to be the opposite of what you want.

**Comment by firewave** [comment]
Thanks for the explanation!

If I understand it right that check would have been fine at least for us since the same configuration was used for httpd certificates and that reported back all the ciphers so that check would have flagged those. But including the extension in the output would highlight, that it is a something that affects the ciphers which is quite useful.

I will do some more tests when that PR is available.

**Comment by lukebakken** [comment]
For what it's worth, the behavior in Erlang/OTP is "more strict" than that in NSS or other x509 implementations. This has caused issues with RabbitMQ users over the past year or so who have been experimenting with limited cipher suites. We're trying to improve our documentation around this edge case, and I plan on summarizing my research an opening an issue with the OTP team.

**Comment by drwetter** [comment]
@dcooper16's improvement has been merged now (with a bunch of other changes) into 2.9dev. 

Therefore I am closing this but would be eager to get feedback ...

**Comment by firewave** [comment]
I tested both systems with the missing "Digital Signature" and I am getting an error message with the httpd one - so as I assumed since we use the same script for both systems this would have highlighted the issue. If we would have just been running Erlang it would have not been obvious.
Maybe the keyUsage check could be integrated with the "Testing cipher categories" highlighting, that certain ciphers might not be available if the implementation were strict. Could be green if available and not colored at all if not available.

**Comment by drwetter** [comment]
> I tested both systems with the missing "Digital Signature" and I am getting an error message

Do you really mean error message? To me such a message means that testssl.sh fails in an expected or non-expected manner.

> Maybe the keyUsage check could be integrated with the "Testing cipher categories" highlighting, that certain ciphers might not be available if the implementation were strict. Could be green if available and not colored at all if not available.

I believe that would not be appropriate but I would love to have a look at the test results. Care for a screen shot or is there any publicly available server where you can point me to?

**Comment by firewave** [comment]
> Do you really mean error message? To me such a message means that testssl.sh fails in an expected or non-expected manner.

Not really - I knew it was ambiguous and I thought I put it in quotes - obviously I meant that I get red text.
```
Server key usage             Key Encipherment
                              -- certificate incorrectly used for digital signatures
```

No public server - just internal test systems. I attached the output of both systems (which some stuff censored out) for you to check.

[httpd.log](https://github.com/drwetter/testssl.sh/files/1664913/httpd.log)
[rabbitmq.log](https://github.com/drwetter/testssl.sh/files/1664914/rabbitmq.log)

```
Android 7.0                  TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 253 bit ECDH (X25519)
```
253 bit?

**Comment by drwetter** [comment]
First for the latter:

https://github.com/openssl/openssl/blob/master/crypto/ec/ecx_meth.c#L20

**Comment by drwetter** [comment]
The logs look ok to me (thx for sending it). I just polished the output a bit further.
