### ISSUE TITLE
False positive: No PFS

### ISSUE THREAD

**Issue by drwetter** [drwetter/testssl.sh#990]
running against my.stbu.net  (85.214.243.213):

```

 Start 2018-02-13 08:15:03        -->> 85.214.243.213:443 (my.stbu.net) <<--

 rDNS (85.214.243.213):  h2082748.stratoserver.net.
 Service detected:       HTTP


 Testing robust (perfect) forward secrecy, (P)FS -- omitting Null Authentication/Encryption, 3DES, RC4 

 No ciphers supporting Forward Secrecy offered


 Testing server preferences 

 Has server cipher order?     yes (OK)
 Negotiated protocol          TLSv1.2
 Negotiated cipher            ECDHE-RSA-AES128-GCM-SHA256, 570 bit ECDH (B-571)
 Cipher order
    TLSv1.1:   ECDHE-RSA-AES128-SHA ECDHE-RSA-AES256-SHA DHE-RSA-AES128-SHA DHE-RSA-AES256-SHA 
    TLSv1.2:   ECDHE-RSA-AES128-GCM-SHA256 ECDHE-RSA-AES256-GCM-SHA384 ECDHE-RSA-AES128-SHA ECDHE-RSA-AES256-SHA ECDHE-RSA-AES128-SHA256 ECDHE-RSA-AES256-SHA384 DHE-RSA-AES128-GCM-SHA256
               DHE-RSA-AES256-GCM-SHA384 DHE-RSA-AES128-SHA DHE-RSA-AES256-SHA DHE-RSA-AES128-SHA256 


 Done 2018-02-13 08:15:13 [  12s] -->> 85.214.243.213:443 (my.stbu.net) <<--

```

**Comment by dcooper16** [comment]
Hi Dirk,

It seems that this server will respond with "handshake failure" if the list of cipher suites in the ClientHello does not include "00,ff." There are several places in testssl.sh in which `tls_sockets()` is called without including "00,ff" in the list of cipher suites. So, I'm working on a PR that will add "00,ff" wherever it is missing (except in cases where a TLSv1.3 ClientHello is being sent and only TLSv1.3 ciphers are listed).

**Comment by drwetter** [comment]
Hi David, sounds good. Thanks for the quick reply.

**Comment by steffenbusch** [comment]
This problem appears again in 3.0rc3 on the same host.
FYI: The webserver is using JSSE from JDK 11 with TLSv1.3 support enabled (at least Chrome and FF can use it).

**Comment by drwetter** [comment]
confirmed. :-( Thx for checking

**Comment by dcooper16** [comment]
I'll look into this and try to found out why it isn't working. It appears that the problem was a result of PR #994, which was merged about one day after this problem was originally fixed. I just don't know why that commit caused a problem.

**Comment by dcooper16** [comment]
It appears that I was mistaken about #994. #994 added "03,04" to the supported_versions extension. If that changed is backed out, then this server will respond with a TLSv1.2 ServerHello. However, if the supported_versions extension offers "03,04", then the server responds with a handshake failure.

OpenSSL 1.1.1a, however, is able to connect to the server using TLSv1.3. So, there must be some difference between the OpenSSL 1.1.1a ClientHello and the `tls_sockets()` ClientHello (for TLSv1.3) that this server does not like.

**Comment by dcooper16** [comment]
I just submitted PR #990, which seems to fix the problem. It appears that OpenSSL, Firefox, and Chrome all include the psk_key_exchange_modes extension in the TLSv1.3 ClientHello messages, and this server rejects TLSv1.3 ClientHello messages that don't include the extension.

I consider this to be a bug in the server, and so am proposing to add a test for this in `run_grease()`, but since several mainstream clients include the extension in their ClientHello messages, it shouldn't cause any problems for our `tls_sockets()` implementation to include it as well.

**Comment by dcooper16** [comment]
This may be related to https://bugs.openjdk.java.net/browse/JDK-8210334.

**Comment by steffenbusch** [comment]
Thanks for this heads up.
Currently the server is running OpenJDK 11.0.1. I can check if the behaviour is changing when the Fix for the bug you've mentioned is made available in the upcoming 11.0.2.

**Comment by drwetter** [comment]
Looks way better now. Great work!

> and so am proposing to add a test for this in run_grease(), but since several mainstream clients include the extension in their ClientHello messages

Sure.

> it shouldn't cause any problems for our tls_sockets() implementation to include it as well.

you mean 2 different tries, one with, another one without the psk_key_exchange_modes extension?

**Comment by dcooper16** [comment]
> you mean 2 different tries, one with, another one without the psk_key_exchange_modes extension?

No. Now that #1170 has been merged, `tls_sockets()` always includes the psk_key_exchange_modes extension in a TLSv1.3 ClientHello. I don't think there is a need to try again without the extension if the first try fails. It seems unlikely to me that a server would support TLSv1.3, but would fail on connection attempts from both Chrome and Firefox.

If I understand correctly, a client would include the psk_key_exchange_modes extension in the ClientHello in order to support session resumption. So, even if a server doesn't support session resumption, it should be prepared for the possibility that a client would send this extension.

If all of the major clients always include this extension in their TLSv1.3 ClientHello messages, it isn't surprising that someone implementing a server could mistakenly not be prepared for the possibility that the extension isn't present in the ClientHello, which is why a `run_grease()` test for that might be useful.

**Comment by drwetter** [comment]
> I don't think there is a need to try again without the extension if the first try fails

Yup. Seems I misunderstood you
